### ISSUE TITLE
עמוד הלוואות

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#100]
בעמוד אליו יגיעו אחרי שילחצו על כפתור הלוואות בעמוד הבית/נחיתה 
צריך להציג את האופציות הבאות
- [x] לאחר לחיצה על כל אחת מן האופציות המופיעות כאן - זה יכול להיות בכפתורים או ברולר כזה שנפתח אחרי שלוחצים על בחר בסוג ההלוואה הרצויה - מה שתבחר כרגע
- [x] יש להוסיף גם סכום הלוואה נבחר
![image](https://cloud.githubusercontent.com/assets/13170174/9291115/3eaef9fe-43b8-11e5-972f-9909c6c129b0.png)
אחרי שלחצו על סוג ההלוואה טופס הזנת הפרטים האישיים זהה
בכל הסוגים
כאן יש דוגמא לרולר שנפתח - ופרטים מזהים ראשונים
![image](https://cloud.githubusercontent.com/assets/13170174/9291120/5658276a-43b8-11e5-9913-98d678a6c46f.png)

צריך לעשות טופס זהה לכאן - גם מבחינת ההדרגתיות שבו - כלומר עמוד ראשון ממלאים רק את הסוג ואת הפרטים הראשוניים
ורק בהמשך זה פותח טופס מתקדם יותר
![image](https://cloud.githubusercontent.com/assets/13170174/9291137/a1ae793a-43b8-11e5-9733-2ad30153971a.png)
![image](https://cloud.githubusercontent.com/assets/13170174/9291147/1cc4e7e4-43b9-11e5-8dc1-5d777045ebf8.png)

כאן יש קלוז-אפ על החלק התחתון של הטופס האחרון
שים לב לכותרת בצד שכל הזמן מתקדמת כך שאתה יודע כמה שלבים נשארו לך לתהליך ההרשמה ובקשת ההלוואה

![image](https://cloud.githubusercontent.com/assets/13170174/9291149/26eed54a-43b9-11e5-861f-9e0181f4d44d.png)

## צד ספק
צריכה להיות רשימה/טבלה של הלקוחות החדשים שהעלו את פרטיהם 
שם, שם משפחה, ת.ז. ומקום מגורים
לחיצה עלהם תפתח עמוד לקוח בו כל הפרטים שהוא הזין - למעט פרטי כרטיס האשראי שלו
בתחתית העמוד צריכים להיות מספר כפתורים
שלח הודעת דחיה
התקדם בתהליך הבדיקה
אשר הלוואה
בצבעים שונים

צריך להבין שסוג הספקים שיהיו רלוונטים להלואות לרוב לא עושים שיקים
אלה ספקים שונים
זאת אומרת שבהרשמת ספק- צריך לשלוח לו לינק של ספק הלוואות
כדי שלא יראה את השיקים

## זה עולה כסף לראות

מבחינת מטח וניכיון שיקים - אלה לרוב ספקים זהים

מה גם ישנם ספקים שעושים רק מט"ח ואז גם להם לא הייתי מעוניין לאפשר לראות את השיקים אם הם לא משחקים במשחק

ז"א שצריך לחשוב על דרך טובה לשלוט בהרשאות שיש לאותם ספקים במידע שהם רואים

**Comment by iddanh** [comment]
תוכל להוסיף תמונת מסך עם האופציות שיש בערך של "יום פירעון רצוי" בבקשה?
בעמוד פרטי חשבון בנק ואשראי
תודה!

**Comment by Sabanini** [comment]
5 לחודש
10 לחודש
15 לחודש
25 לחודש
2 לחודש
בתאריך 1 בספט׳ 2015 21:30,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
איך עובד הצעה של ספק על הלוואה?

**Comment by Sabanini** [comment]
לא הבנתי. מה השאלה
בתאריך 5 בספט׳ 2015 14:11,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
בתחתית העמוד צריכים להיות מספר כפתורים
שלח הודעת דחיה
התקדם בתהליך הבדיקה
אשר הלוואה

מה כל כפתור עושה?

**Comment by Sabanini** [comment]
אלה כפתורים בצד הספק
שלח הודעת דחיה מעביר את הבקשה לעמוד בקשות שנדחו.

התקדם בתהליך הבדיקה זה בעצם שחסר לו מסמך או נתון כלשהו ואז צריך לחשוב מה
בור דורש

אשר הלוואה זה האישור שאמור לפתוח מחשבון מתן הלוואה

**Comment by Sabanini** [comment]
אלה כפתורים בצד הספק


שלח הודעת דחיה מעביר את הבקשה לעמוד בקשות שנדחו. ומוחק את הבקשה מבקשות
חדשות.

התקדם בתהליך הבדיקה זה בעצם שהלקוח מעניין אותו אבל חסר לו מסמך או נתון
כלשהו לצורך קבלת החלטת מתן האשאי הסופית ואז צריך לפתוח לו רולר של מסמכים
נוספים כמו בשיקים, אבל עם מסמכים שונים:


   - צילום תעודת זהות
   - תלוש משכורת 3 חודשים אחרונים
   - תדפיס חשבון בנק/ים 3 חודשים אחרונים
   - דוח פירוט יתרות/פירוט הלוואות
   - צילום שיק מבוטל
   - צילום רישיון רכב
   - צילום חשבון ארנונה
   - אישור בעלות על נכס
   -

אשר הלוואה זה האישור שאמור לפתוח מחשבון מתן הלוואה בדיוק כמו בשיקים רק
שהפרמטרים הם שונים


   - [image: תמונה מוטבעת 1]
   -  הסכום ברוטו שממנו מתחיל המחשבון לשלם זה סכום ההלוואה הנדרש
   - דמי טיפול נשארים  אותו דבר
   - ימי ערך להוריד - אבל לא לשכוח לחשב את הריבית במשך התקופה הנדרשת - כאשר
   ברירת המחדל היא דרישת הלקוח (3 שנים- 5שנים וכו') - אבל לספק יש יכולת לשנות
   את התקופה בחודשים..
   - להוסיף פרמטר של החזר חודשי
   - ריבית נשארת רק יש לשנותה לריבית שנתית
   - עמלת העברה- לשנות לעמלת עריכת מסמכי המת הלוואה..

זהו שיהיה לנו בהצלחה


בתאריך 5 בספטמבר 2015 בשעה 17:25, מאת ניר סבן <saban.nir@gmail.com>:

> אלה כפתורים בצד הספק
> שלח הודעת דחיה מעביר את הבקשה לעמוד בקשות שנדחו.
>
> התקדם בתהליך הבדיקה זה בעצם שחסר לו מסמך או נתון כלשהו ואז צריך לחשוב מה
> בור דורש
>
> אשר הלוואה זה האישור שאמור לפתוח מחשבון מתן הלוואה
>

**Comment by iddanh** [comment]
אולי נעשה כמו בשיקים שהבקשה של הפרטים הנוספים באה כחלק מההצעת מחיר?
כלומר באופציה של אישור הלוואה ליד המחשבון יופיע הרולר עם האופציות למידע נוסף

חוץ מזה מה זה הפרמטר של החזר חודשי?

**Comment by Sabanini** [comment]
בהלוואה הטופס שממלאים הוא רשימת  נתונים קבועים מראש שהספק צריך כדי לקבל
החלטה,  ואין סיטואציה שהספק לא צריך משהו מתוך זה.
ייתכן כן שבעתיד נשנה את הרכב הרשימה נוסיף או נוריד פרמטרים אבל מה שברשימת
הנתונים שבטופס הלקוח חייב למלא..

ההחזר החודשי זה למעשה כמה הלקוח יחזיר כל חודש מההלוואה
הוא רושם את זה בטופס כי זה בעצם תנאי העסקה שהוא מבקש בבקשה שלו.
20 אלף לשנתיים עם החזר של אלך כל חודש.

זה פשוט אחד הפרמטרים בעסקה, מעבר לפרמטרים שלו לקבלת ההחלטת אשראי

אולי נעשה כמו בשיקים שהבקשה של הפרטים הנוספים באה כחלק מההצעת מחיר?
כלומר באופציה של אישור הלוואה ליד המחשבון יופיע הרולר עם האופציות למידע נוסף

חוץ מזה מה זה הפרמטר של החזר חודשי?

—
Reply to this email directly or view it on GitHub
<https://github.com/iddanh/BillyDemo/issues/100#issuecomment-140187063>.

**Comment by iddanh** [comment]
נראה לי שלא הבנת אותי

כשאמרת:
התקדם בתהליך הבדיקה זה בעצם שהלקוח מעניין אותו אבל חסר לו מסמך או נתון

אתה אומר שהספק יבקש את הנתון הזה וזהו
אני רוצה שהוא כבר יציע הצעה (כמו בשיקים) בהתניה שהלקוח יתן את המידע הזה

-----

את הפרמטר של החזר חודשי קובע הספק בהצעה או הלקוח בבקשה?

**Comment by Sabanini** [comment]
אז גם בשיקים מסמכים נוספים זה כאב ראש שחלק מהספקים לא מתעסקים איתו וחלק כן
כמעט בכל עסקה

בנוגע להלוואות,  הספק צריך מסמכים נוספים בין כה וכה אבל את הטופס הוא חייב
בלי קשר,

ואין תי בעיה פה של שיווק
כי פה אנחנו לא ממציאים משהו
מי שמבקש הלוואה יודע שהוא צריך למלא טופס עם כל הפרטים

בשיקים אנחנו עושים משהו טיפה חדשני בזה שהבן אדם לא ניגש לחברה פיזית
או לא שולח צילום שיק בפקס

אלא מעלה את הפרטים שלו למערכת

אז אין לחץ על הטופס שת ההלוואה

ואני מציע שפשוט כפרופאוב קונצפט תעשה שטופס שלקוח ממלא מגיע לעיני הספק
המתאים ,

מה מופיע בטופס זה בטוח יהיה נתון לשינויים
אז אין מה כרגע להתעסק עם התוכן עצמו של הפרמטרים בטופס
בתאריך 14 בספט׳ 2015 23:15,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
הוספתי הצעות מחיר מצד ספק (עם מחשבון) ואישור שלהם בצד לקוח
מחר אוסיף אופציה לבקשת מסמכים נוספים

**Comment by iddanh** [comment]
סיימתי! 
אשמח אם תוכל לבדוק שהכל עובד פיקס
במיוחד את החלק עם הבקשת מסמכים נוספים

**Comment by Sabanini** [comment]
סגור אני על זה.

סתם שתדע שאני לומד את השוק האמריקאי, של הפקטורינג, בימים אלו,
כמו שזה נראה כרגע כדי לשחק במגרש של הגדולים נהיה חייבים להראות יכולות גם
בשוק העולמי..

כנס בבקשה לאתר של

Fundbox
Bluevine ו-

ותראה איך הם שואבים ממערכות הנהלת החשבונות של הלקוחות את החשבוניות שטרם
נפרעו באופן אוטומטי עי יבוא של המערכת שלהם מהתוכנה שייצרה את החשבוניות , זה
למעשה חיסכון בפעולות העלאת השיק והזנת הנתונים,
בנוסף, מאותו רגע של סינכרון, פאנדבוקס מתחילה ללמוד אודות העסק, ואיתנותו
הפיננסית, כי היא התחברה לתוכנת ההנהלת חשבונות שלו ואז יכולת קבלת ההחלטה אם
לתת אשראי או לא כבר זמינה לו..
ואז הוא מתמחר כל חשבונית לניכוי בהתאם לסיכון הכרוך בה. משלל הנתונים שקיבל.
פה הם טוענים שהם בנו רובוט שקובע את המחיר לבד.

אנחנו נבמע השוואה בינם לבין אחרים בשוק, ואחרים שיקומו בעקבותם..
כי הל תמיד ינסו לקחת יותר, ותמיד יהיו פערים בין החברות, וכאשר לקוח רוצה את
המחיר הטוב ביותר עבור החשבונית שלו הוא ישווה...

התהליך הזה מאוד דומה לניכיון שיקים.

והוא מתקיים בארה"ב והוא כרגע בהתפתחות מטורפת..
אם אנחנו נצליח לבצע את ההשוואה בין החברות שעושות את הפעולה הזו בזמן אמת,
ע"י זה שנשווה את המחירים שהם נותנים על כל חשבונית,

ניצחנו
בתאריך 19 באוק׳ 2015 00:11,‏ "iddanh" <notifications@github.com> כתב:
