### ISSUE TITLE
העלאת שיק מחדש

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#105]
- [x] יש לשנות את כותרת העמוד לעסקאות שבוטלו - ובמידה ועסקה בוטלה - יש לשים כפתור בסוף השיקים שיופיעו שם 

## 'העלה שיק מחדש'
- [x] כדי לאפשר ללקוח להעלות את השיק שקיבל הצעת מחיר אושר ונדחה על ידי חברת הניכיון להעלות אותו מחדש ולקבל חזרה את כל ההצעות הקודמות שקיבל אם קיבל
זה בעצם שחזור כל ההצעות הקודמות שקיבל השיק 
למעט ההצעה שהוא אישר שבוטלה 

![image](https://cloud.githubusercontent.com/assets/13170174/9309229/e4f75c94-4510-11e5-9a88-25a9e1d84e5c.png)

## חשוב
- [x] לחיצה על כפתור - העלה שיק מחדש - תדרוש ממנו הזנת סיסמא
שאנחנו ניתן לו
כלומר ביצוע פעולת שיחזור תתאפשר רק לאחר שקיבל מאיתנו אישור על כך

הרי יכול לקוח לאשר עסקה, לחשוף את הספק, לדווח על ביטולה ולאשר עוד אחת וחוזר חלילה
רק באישור של האדמיניסטרטור  הוא יוכל לעשות זאת,
וזאת לאחר שאנחנו נברר מה הייתה סיבת הביטול והאם הוא הגיע לחברת הניכיון ומה הייתה הסיבה לדחייה

**Comment by iddanh** [comment]
אפשר העלאה מחדש לא בדמו?

**Comment by Sabanini** [comment]
רק אחרי אישור
בתאריך 18 באוג׳ 2015 19:36,‏ "iddanh" <notifications@github.com> כתב:

**Comment by Sabanini** [comment]
כי אם באמת עשו לו עוול, והוא הלך והיה סכור או שהם הפרו את ההתחייבות שלהם,
עד שנטפל בהם, הבחור רוצה עסקה, ככה שאני מחזיר לו את ההצעות שכבר נתנו לו,
האחרין לא יודעים מזה והוא מבסוט
בתאריך 18 באוג׳ 2015 19:39,‏ saban.nir@gmail.com כתב:

**Comment by iddanh** [comment]
במקום שנצטרך ליצור קוד אישור ולתת אותו למשתמש להכניס כשהוא רוצה לשחזר
אני פשוט אשים את החלק של השחזור בעמוד של האדמין
סבבה?

**Comment by Sabanini** [comment]
חיובי
בתאריך 18 באוג׳ 2015 22:07,‏ "iddanh" <notifications@github.com> כתב:
