### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by iddanh** [iddanh/BillyDemo#106]
בחרתי כמה אופציות שנראות טוב לדעתי
1. http://themicon.co/theme/angle/v3.0/frontend/site/
2. http://htmlstream.com/preview/unify-v1.8/
3. http://htmlcoder.me/preview/the_project/v.1.0/
4. http://bootstraplovers.com/templates/assan-v1.8/
5. http://htmlcoder.me/preview/idea/v.1.2.1/html/

תבחר איזה אחד נראה לך הכי יפה

טמפלטס עם אופציה RTL
1, 2

אתה יכול לחפש עוד כאן אם אתה רוצה
https://wrapbootstrap.com/themes/

תחפש כאלה שהם לא dashboard
ותראה אם יש אופציה לRTL

**Comment by iddanh** [comment]
בחרנו 
http://htmlstream.com/preview/unify-v1.8/

**Comment by ranbyt** [comment]
נראה מעולה
