### ISSUE TITLE
שדרוג עמוד התחברות- ניכיון צ'קים

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#110]
עידן כפרה זה רן. מה עניינים
רעיון שעלה- בשביל שנוכל לשמר את המידע של לקוחות ולתפוס אותם לפני שהם "התעייפו"/ התחרטו במילוי טופס ההתחברות ( צריך לוודא ששומרים את כל המידע שהם מקלידים בתיבה בטופס גם אם הם לא עשו "
שלח" בכדי שאם לקוח מילא את השלב הראשון ולא המשיך למלא את כל הטופס, נציג שלנו יוכל חזור אליו ולבדוק איתו למה הוא לא השלים את התהליך
נחלק את הטופס ל-3-4  שלבים
שלב ראשון- שם, שם חברה, טלפון, דוא"ל
שלב שני- פרטי העסק
שלב שלישי- פרטי נציג העסק
שלב רביעי- פרטי התחברות

מבינים שזה הופך את הסדר שקיים עד כה, אבל זה חשוב שיווקית לתפוס מתנדנדים

**Comment by iddanh** [comment]
אז לא חילקתי את זה בדיוק ככה
אבל השלב הראשון כולל אימייל ושם
זה נשמר גם אם הוא לא מסיים את ההרשמה
אז אם הוא מוותר אחרי זה אפשר לשלוח לו מייל
