### ISSUE TITLE
 analytics 

### ISSUE THREAD

**Issue by ranbyt** [iddanh/BillyDemo#112]
לא יודע אם כבר דיברתם על זה, אבל חשוב שיהיה לנו כלי ניתוח ובקרה על האתר מעבר לנתונים הרגילים שיש באנליטיקס כמו מיקום, מערכת הפעלה, שפה וכו,  
 צריך טיקר על כל מסך וכפתור,  בכדי שנוכל ללמוד
על הפעילות של המשתמשים שלנו,  איזה כפתור עובד/איזה כיתוב לא עובד וכו

**Comment by ranbyt** [comment]
דומה לסוגיה #80

**Comment by Sabanini** [comment]
שים לב לאתר השוואת ביטוח
איך הם ניתחו את האנליטיקס - מה הם ביקשו לדעת על כל כניסה 

F12 על העמוד שאתה בו בדפדפן


![image](https://cloud.githubusercontent.com/assets/13170174/9981157/55c94484-5fbd-11e5-9caf-1477582a881a.png)

**Comment by iddanh** [comment]
![image](https://cloud.githubusercontent.com/assets/12518219/10541342/f5ce9c58-7418-11e5-8b3a-1f7b2b110c6e.png)

היה לנו מבקר מקרואטיה!
