### ISSUE TITLE
באג באג  צד ספק

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#118]
כשספק בעמוד הלוואות
![image](https://cloud.githubusercontent.com/assets/13170174/9698149/430567d6-53b2-11e5-9dff-bd3cc5663019.png)

ולוחץ על מחלקת מט"ח
מתקבל הבאג הבא

![image](https://cloud.githubusercontent.com/assets/13170174/9698141/0fe40a92-53b2-11e5-85fb-4d2fc9929c98.png)

גם מתוך עמוד שיקים כשלחצתי על מט"ח 
זה מה שהתקבל
![image](https://cloud.githubusercontent.com/assets/13170174/9698163/b0e638ca-53b2-11e5-85d1-1c0788463a71.png)

**Comment by Sabanini** [comment]
זה עדיין ככה

**Comment by iddanh** [comment]
עוד לא העלתי
