### ISSUE TITLE
שינוי חשוב בדשבורד ספק

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#119]
אני חושב שאת סרגל האופציות של 
ניכיון
מטח 
והלוואות

![image](https://cloud.githubusercontent.com/assets/13170174/9698172/f969e2f4-53b2-11e5-9d80-08abbed5363f.png)

צריך לשים בעמוד אדמין בלבד
ורק אם אנחנו אישרנו את הספק רק אז הוא יוכל לעבור ממחלקה למחלקה

מה שקורה עכשיו לא תקין
כי ספק לא יכול לבחור שהוא פתאום זה פתאום רק זה 
מדובר במערכת שונה לגמרי
בו בזמן שלפני הספק חותם מולנו על הסכמים
הוא לא רשאי להחשף לכל המידע 

לכן אני חושב שהסרגל כפתורים
אופציות הספק מצויין
רק שצריך למקם אותו בדשבורד אדמין

אני חושב שבשלב הזה צריך להעלים את הסרגל מהדשבורד של הספק ולהעעבירו לאדמין

ולגבי נושא ההרשמה וכולי נחשוב על זה בהמשך
כי זה עניין מעט מורכב
כי מדובר בספקים שונים

דיברנו על זה כבר...

**Comment by Sabanini** [comment]
גם פה יש בעיה עם העובדה שאותו לקוח יכול גם לבקש הלוואה וגם מטח בהינף יד, זה לא הגיוני
אנחנו צריכים לדעתי לשנות את זה

![image](https://cloud.githubusercontent.com/assets/13170174/9700022/0893265a-53fe-11e5-89df-103d2279dad8.png)

ופשוט להחליט שכל סוג של לקוח נרשם בנפרד לשירות אותו הוא רוצה

מי שמנכה שיקים צריך את השירות שלנו באופן שוטף כל כמה ימים או שבועות
אלה שצריכים הלוואות צריכים את השירות שלנו אחת לשנה או מקסימום חצי שנה
ואלה של המטח זה גם בתדירות יחסית לא נשלטת פה ושם...

אין תדירות בהלוואות
תחשוב שהלוואה נפרעת בשלוש שנים, ככה שעד שהם יצטרכו או יקחו הלוואה נוספת יכולה לעבור תקופה יחסית ארוכה
ז"א שהיכולת של לקוח לזגזג בין מחלקה למחלקה לא נדרשת
ואולי טעינו בהתחלה שסברנו ככה

אני חושב שהפתרון יהיה כזה
בעמוד הבית יהיו שלושה כפתורים גדולים שדרכם הלקוחות ירשמו
ניכיון שיקים
הלוואות לכל מטרה
המרת מט"ח

ברגע שלקוח לוחץ עליהם הוא יכול או להתחבר או להירשם לראשונה
וכך בהתאם לכל מחלקה ההרשמה שונה



(תחילה הם נרשמים עם מייל וסיסמא ואז נכנסים לאיזור אישי ( כמו ביד שתיים למשל
באיזור האישי אם נרשמת כניכיון אתה יכול להתחיל להעלות שיקים רק אחרי שמילאת את הטופס הראשוני
אם נרשמת להלוואות אתה מעלה בקשה אחרי שמילאת את הטופס של הפרטים הדרושים
אם נרשמת תחת המרת מטח אתה פשוט מעלה את הסכום הדרוש לך להחלפה ומקבל הצעות
אין צורך בפרטים נוספים

כך לכל לקוח יש יוזר וסיסמא
והוא ממויין למחלקה אחרת
גם אם מישהו משתמש באותם נתוני מייל וסיסמא, אין בעיה כי הזיהוי שלו הוא משולש, מחלקה מייל וסיסמא - וכך אנחנו מבדילים בינהם
אם מישהו התחבר לניכיון ובמקרה פתאום בא לו לבקש מטח, הוא יכול מתוך המחלקה שלו לעבור אבל הוא יהיה חייב להירשם ואם כבר נרשם אז להתחבר אבל במחלקה השניה - המרת מט"ח..

קומפרנדה?

**Comment by iddanh** [comment]
אוקיי אבל אפשר לא לדמו?
כבר עשיתי את כל התשתית וזה ייקח הרבה זמן לעשות את זה שוב עכשיו

**Comment by Sabanini** [comment]
כן.
אבל ייתכן שנצטרך פשוט לנטרל את היכולת לעבור ממחלקה למחלקה וזהו.
כלומר להשאיר את הניכיון לבד
כי ההתחלה תהיה בעיקר ללקוחות הניכיון
ואני לא רוצה שישוטטו במחלקות לא קשורות
בתאריך 5 בספט׳ 2015 19:17,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
החלק הראשון של הסוגיה סבבה

**Comment by Sabanini** [comment]
מה אתה חושב על הרעיון שהצעתי בנוגע להרשאות ולסיסמאות
שבעמוד הבית יש שלושה כפתורים ומשם נרשמים או מתחברים?
וכל מחלקה עומדת בפני עצמה


2015-09-05 19:31 GMT+03:00 iddanh <notifications@github.com>:

**Comment by iddanh** [comment]
אני דווקא חושב שיותר קל לאנשים להבין שיש להם משתמש בבילי
ואז אחרי שהם התחברו אפשר להחליט לאיזה מחלקה ללכת

אם לכל מחלקה יש רישום מחדש אז זה אומר שאני צריך שיהיה אצלי שלושה טבלאות שונות של משתמשים,
ויכול להיווצר מצב שלאותו משתמש יש נתוני התחברות שונים בין המחלקות אם נגיד תפסו לו את השם 

ככה גוגל עושים, יש לך משתמש אחד בגוגל, ואתה יכול להשתמש באותו אחד לג'ימייל או יוטוב או גוגל פלוס וכו וכו

**Comment by Sabanini** [comment]
לזה התכוונתי,  שיהיה להם מייל אחד, שהוא היוזר.
אבל כן יש שלוש טבלאות,

המייל aaa בהרשמה לניכיון
המייל aaa בהרשמה להלוואות
המייל aaa בהרשמה למט"ח

כולם בצירוף סיסמא.

זה נראה לי יותר נכון,  כי זה לא בהכרח אותם לקוחות,
בתאריך 8 בספט׳ 2015 19:57,‏ "iddanh" <notifications@github.com> כתב:

**Comment by ranbyt** [comment]
אני מסכים עם עידן,  שמשתמש נרשם הוא אח"כ בוחר את הפעילויות שהוא רוצה
לעשות,  קודם שירשם

Ran Bytton Eshel

**Comment by iddanh** [comment]
אין בעיה שזה לא אותם לקוחות, לכל לקוח אני אשמור מה המחלקות שהוא שייך להם

נגיד לקוח נרשם עם אימייל וסיסמא למטח
ואז אחרי חודש הוא רוצה גם שיקים
אז הוא עובר למחלקה של שיקים ובגלל שכבר יש לו משתמש בבילי הוא רק ממלא את הפרטים על עצמו
לא צריך מייל וסיסמא שוב, כבר יש לי את זה

**Comment by Sabanini** [comment]
לסכם את הדברים
הבנתי מה אתם מתכוונים ובסדר כרגע לעשות

בנוגע לשם המשתמש
חשוב לעשות שימוש במייל פעיל
כרגע אנחנו לא מחייבים זאת,
אבל זה ידרש במוקדם או במאוחר
אז בוא ננסה כבר עכשיו לראות איך אנחנו דואגים שזו האופציה היחידה להרשם 

עם מייל הפעלה או משהו כזה, כדי להיות בטוחים, שפעיל ולא סתם

תחשוב שזו גם הדרך שלנו לשלוח לו עידכונים או הודעות
אם עלו שיקים חדשים הצעות חדשות, וגם מבחינה משפטית זה יותר מזהה את הבנאדם

בהמשך נוכל גם לדרוש זאת ממס הנייד שלו, 
שיקבל סמס וכול..
אנחנו מפחדים מפרודים, לכן צריך כל הזמן לחשוב שמנסים לעבוד עלינו
גם הספקים וגם הלקוחות...

אולי נשלח לו מיי רישום או משהו כזה

**Comment by iddanh** [comment]
מייל הפעלה נשמע טוב
אבל בוא נשמור את זה לאמיתי

**Comment by ranbyt** [comment]
שווה לבדוק לעבוד עם mail chimp לכל המיילים האלה וגם ניוזלטר וכו

Ran Bytton Eshel
