### ISSUE TITLE
עניינים קטנים בהלאוות

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#121]
הרולר של סכום ההלוואה לא זז אם אני גורר אותו
רק אם אני משנה את הסכום מהצד הוא זז בהתאם

לדעתי בעבר זה עבד

![image](https://cloud.githubusercontent.com/assets/13170174/9698227/670c8cf6-53b5-11e5-8d71-d906afad838d.png)

אל תתחיל עם אלמנה 
פשוט תהפוך את הסדר של הרשימה כמו שהיא
כשרווק ראשון

![image](https://cloud.githubusercontent.com/assets/13170174/9698225/58d9cfc2-53b5-11e5-99f6-aabc2952e072.png)

![image](https://cloud.githubusercontent.com/assets/13170174/9698245/1d9f6a42-53b6-11e5-9993-e331e29c6e7f.png)

יש פה טעות כתיב קטנה
מקבל קצבה

אם לקוח לוחץ על הבקשת הלוואה שהוא העלה
הוא מגיע לעמוד הזה

![image](https://cloud.githubusercontent.com/assets/13170174/9698250/7ac4192a-53b6-11e5-915b-efffea831ec7.png)

כרגע תשאיר שלחיצה לא עושה כלום בהמשך אולי ניתן לו אפשרות לערוך את בקשתו
או אם זה זריז
תעשה כבר
![image](https://cloud.githubusercontent.com/assets/13170174/9698256/ccf65fa0-53b6-11e5-9331-3a9f23f5b137.png)

**Comment by iddanh** [comment]
אצלי נראה שהרולר עובד
