### ISSUE TITLE
שינוי בברירת מחדל של עמוד הגדרות לקוח

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#122]
בעמוד הזה
![image](https://cloud.githubusercontent.com/assets/13170174/9795525/e101a1a2-57f9-11e5-9c83-ecaf07a2fd8f.png)

ברירת המחדל של אמצעי התשלום צריכים להיות כל האמצעים

אחרת כשיציעו הספקים ללקוח הצעות מחיר ,
והוא לא ידע שהוא צריך למלא את המשבצות הוא לא יראה הצעות
עד שימלא

אז ברירת המחדל צריכה להיות שכולם מסומנים
ואם הוא ספציפי לא ירצה לראות אמצעי תשלום מסויימים אז שבהמשך יסיר מה שבא לו

**Comment by iddanh** [comment]
זה כבר ככה
לא?

**Comment by Sabanini** [comment]
האמת שכן ראיתי את זה אחרי זה


2015-09-11 14:50 GMT+03:00 iddanh <notifications@github.com>:
