### ISSUE TITLE
באג באג באישור הצעת מחיר

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#126]
![image](https://cloud.githubusercontent.com/assets/13170174/9799860/63b3338c-5812-11e5-964d-634ba362ac08.png)

**Comment by iddanh** [comment]
עשיתי כמה שינויים, תוכל לבדוק אם זה עדיין קורה?

**Comment by iddanh** [comment]
אפשר לסגור?

**Comment by Sabanini** [comment]
יש עדיין בעיות באישור הגדרות בברירות מחדל
לדוגמא במטח

כנראה שהסיבה שהספקים לא רואים את הבקשות החדשות זה בגלל שהם לא מילאו את המטבעות שהם ממירים

אבל כניסיתי לסמן את המטבעות
כפתור 
אישר
לא עבד לי. . ר
