### ISSUE TITLE
לעשות שהאתר כשיחפשו בגוגל אותו יראה את כל העמודים שבו, תחת הכותרת שלו

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#127]
ככה
![image](https://cloud.githubusercontent.com/assets/13170174/9822603/f15981f2-58c9-11e5-9665-6c89666a6fd1.png)

**Comment by iddanh** [comment]
https://support.google.com/webmasters/answer/47334
זה קורה אוטומטית אם גוגל חושב שאנחנו מספיק חשובים.... ננסה להיות כמה שיותר חשובים :)

**Comment by Sabanini** [comment]
ב
wix
זה קורה אוטומטית

אז צריך להבין מה הם עושים
איפה הם עובדים על גוגל ולעשות את זה...

חפש בוויקס support

**Comment by Sabanini** [comment]
https://www.wix.com/support/html5/search-engine-optimization/site-visibility-in-search-results/kb/enabling-search-engines-eg-google-to-find-your-site

**Comment by iddanh** [comment]
כן יש קונסול ב
google webmasters
שאפשר לעשות שם כל מיני דברים

אני יעשה את זה אחרי שאני אסיים לבנות את הדמו
