### ISSUE TITLE
הערות לעמוד הבית - לעמוד איך זה עובד  -  לעמוד אודות

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#128]
## עמוד הבית

- [x] - להעביר את הכותרות : דף הבית, אודות, איך זה עובד, צור קשר, שירות ותמיכה - ימינה ולהחליף צדדים עם הלוגו שאמור להיות בצד שמאל

- [x] - להוסיף בשורת menu 
למעלה אחרי איך זה עובד 
השאוות ניכיון, השוואת מט"ח, השוואת הלוואות 
הלחיצה תעביר אותך אל עמוד ההתחברות לעמוד שנבחר..

- [x] -  להחליף את הסדר בין צור קשר לתמיכה - הצור קשר צריך להיות אחרון בשורה

- [x] - לשנות את המילים שרצות על התמונה ל- השוואת עסקאות ניכיון שיקים
השוואת הלוואות
השוואת עסקאות מט"ח

- [x] - את המילה "התחברות" - שבראש העמוד משמאל למעלה -  להגדיל את גודל הפונט
"בנוסף - להוריד את "עזרה" ו"תנאי שימוש

- [x] - כרגע תוריד את התמונה של השיק הירוק

- [x] -לעשות ש לחיצה על הלוגו מכל העמודים תמיד מובילה לעמוד הבית

- [x] - את המשפט
אתר בילי מברך את הצטרפותכם לאתר בילי - להשוואת עסקאות ניכיון שיקים, המרת מט"ח והלוואות
באתר בילי תוכלו לחסוך את עמלות הניכיון, להקטין משמעותית את שיעורי הריבית ולהגדיל את מסגרות אשראי הניכיון לעסקך

לשנות ל- 
(כותרת)
אתר בילי מברך את הצטרפותכם לציבור החוסכים
בילי - מנוע להשוואת עסקאות ניכיון שיקים, עסקאות מט"ח והלוואות
(ובקטן יותר)
מערכת ממוחשבת באמצעותה תוכלו לחסוך את עמלות הניכיון, להקטין משמעותית את שיעורי הריבית ולהגדיל משמעותית את מסגרות האשראי לעסקך

(מתחת)
מעלים - שיקים  אל המערכת באמצעות הנייד או המחשב
משווים - עסקאות מבין כלל הצעות המחיר שקיבלתם
מבצעים - את העסקה אצל החברה שנבחרה 
וחוסכים - עמלות ריביות וריצות מיותרות 

## עמוד איך זה עובד
- [x] - "להעביר את הטקסט הקיים תחת עמוד "עזרה 
להוסיף כפתור "עזרה" במערכת עצמה - כלומר כפתור שנגיש רק למי שכבר נרשם למערכת ועובד איתה
אין סיבה שמי שלא נרשם יחשף לכל המידע הזה
מדובר על כפתור שנגיש רק ללקוחות הניכיון שיקים, מי שצריך הלוואה זה לא רלוונטי עבורו,
לאלה נכין בהמשך טקסט אחר..

- [x] - "כן להשאיר את הכותרת "איך זה עובד
ולרשום מתחתה את המשפטים הבאים:
( בכל משפט המילה הראשונה בבולט ובצבע אחר ואז להוריד את המקף)
מעלים - שיקים  אל המערכת באמצעות הנייד או המחשב
משווים - עסקאות מבין כלל הצעות המחיר שקיבלתם
מבצעים - את העסקה אצל החברה שנבחרה 
וחוסכים - עמלות ריביות וריצות מיותרות 

לדוגמא
![image](https://cloud.githubusercontent.com/assets/13170174/9835648/acd468d2-59fd-11e5-80e1-7ed35d101a0d.png)

**Comment by iddanh** [comment]
האתר הוא בעברית אז זה 
right to left
כלומר הלוגו צריך להיות מימין והלינקים משמאל

**Comment by Sabanini** [comment]
שים לב פה, 
לפני שאתה משנה דברים יש הרבה ששיניתי כבר
שים לב

**Comment by iddanh** [comment]
אוקיי אז תשלח לי במייל את הקבצים ששינית ואני אשלב אותם

**Comment by Sabanini** [comment]
עניין קטן 
תעשה שלחיצה על אודות מעבירה אוומטית לאודות
אפשר גם לקבל רולר של אפשרויות אם שמים עליו את הסמן של העכבר 
אבל לחיצה על אודות 
מעבירה לעמוד אודות

כרגע רק לחיצה על אודות
תחת אודות מעביר 

מכאן שאפשר 
למחוק את האופציה אודות
מתחת לאודות

זה הרי מיותר


באתר המותאם צריך שתי לחיצות

כלומר לחיצה ראשונה פותחת את הרולר אבל לחיצה שניה מעבירה כבר לעמוד אודות

זא 
שאם מישהו כן רוצה לעבור לעמוד אחר ברולר שנפתח זה מתאפשר לו

**Comment by Sabanini** [comment]
עשיתי שינויים כמעט בכל העמודים של הpublic
אפשר לראות את זה אם אתה נכנס להיסטוריה
בתאריך 14 בספט׳ 2015 13:32,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
אהה כן פתחת ענף חדש! יפה!!!
אני אשלב אותם עכשיו

**Comment by iddanh** [comment]
אז מה מפה כבר עשית ומה נשאר לעשות?

**Comment by Sabanini** [comment]
ממך אני צריך את הטקסט השונה בארבעת המשפטים..
כמו בסופרמרקט
