### ISSUE TITLE
מייל רישום

### ISSUE THREAD

**Issue by iddanh** [iddanh/BillyDemo#135]
סוגיה שמשקפת את הדברים שנאמרו בהערות של #119 

לסכם את הדברים
הבנתי מה אתם מתכוונים ובסדר כרגע לעשות

בנוגע לשם המשתמש
חשוב לעשות שימוש במייל פעיל
כרגע אנחנו לא מחייבים זאת,
אבל זה ידרש במוקדם או במאוחר
אז בוא ננסה כבר עכשיו לראות איך אנחנו דואגים שזו האופציה היחידה להרשם

עם מייל הפעלה או משהו כזה, כדי להיות בטוחים, שפעיל ולא סתם

תחשוב שזו גם הדרך שלנו לשלוח לו עידכונים או הודעות
אם עלו שיקים חדשים הצעות חדשות, וגם מבחינה משפטית זה יותר מזהה את הבנאדם

בהמשך נוכל גם לדרוש זאת ממס הנייד שלו, 
שיקבל סמס וכול..
אנחנו מפחדים מפרודים, לכן צריך כל הזמן לחשוב שמנסים לעבוד עלינו
גם הספקים וגם הלקוחות...

אולי נשלח לו מיי רישום או משהו כזה

**Comment by ranbyt** [comment]
מייל רישום זה מעולה גם לפרוד,  גם לשיווק וגם בכדי שנוכל באמת לכמת משתמשים

Ran Bytton Eshel

**Comment by iddanh** [comment]
עובד!

אני צריך ממך טקסט לשים בעמוד שאומר שנשלח אימייל ובמייל עצמו

**Comment by Sabanini** [comment]
סבבה,
על הדרך תוסיף בבקשה שכחת סיסמא
בתאריך 3 באוק׳ 2015 19:44,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
אל תדאג יש לזה סוגיה משל עצמה
לא שכחתי :smiley:
