### ISSUE TITLE
דש בורד ספק - הלוואות

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#140]
טעות כתיב בפרמטר האחרון
![image](https://cloud.githubusercontent.com/assets/13170174/10567185/18341578-7605-11e5-91f3-98e6033ae36f.png)

ריבועי הבחירה לא עובדים

![image](https://cloud.githubusercontent.com/assets/13170174/10567190/32422112-7605-11e5-8325-ecbc5aa95aaa.png)

המסמך היחידי שעבד היה אחר
אז לחצתי עליו
ולא כתבתי כלום
ושלחתי, 
אז צריך לוודא שנכתב שם משהו

וזה לא ריק
![image](https://cloud.githubusercontent.com/assets/13170174/10567206/73599522-7605-11e5-89de-abb139401d63.png)

מעבר לכך יצירת העמודים טובה מאוד
אבל צריך לחשוב על דרך שבה, אחרי שהלקוח קיבל את דרישת המסמכים, והעלה אותם, איך הבקשה חוזרת  להיות בכותרת של הספק,
מה מניע אותו להמשיך לטפל בלקוח המצטיין שפעל נמרצות לפתור את הבעיה של הספק/את החוסר שיש לו במסמכים וידע לצורך קבלת ההחלטה

לכן אחרי שהלקוח משיב את המסמך, יש להחזיר אותו לרשימת הצעות חדשות - עם סימון כלשהו שהוא כבר סיבוב שני, ושיש תוספת מסמכים

בנוסף אני חושב שצריך לאפשר ללקוח מלכתחילה להעלות מסמכים בבקשה עצמה,
 באופן וולונטרי, ככה אם הלקוח יודע בוודאות שיבקשו ממנו בהמשך את המסמכים האלה 
עדיף לאפשר לו לחסוך עבודה למערכת 
ולהעלות אותם מראש...

**Comment by iddanh** [comment]
לא הבנתי מה אמור להיות במקום הטעות כתיב, ככה גם אתה כתבת בסוגיה...
