### ISSUE TITLE
 צד הלקוח: בעמוד הצעות מחיר מפורטות

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#17]
יש להשמיט את כל הפרמטרים שהובילו לסכום נטו שהתקבל 
את הלקוח זה לא מעניין כמה עלמה לקחו לו על דמי הטיפול
אותו מעניין איפה נשאר לו הכי הרבה כסף
אחרי הפעולה של הניכיון

מבחינה עיצובית - 
פרטי הלקוח והשיק צריכים להיות למעלה כמו שזה עכשיו ומיד ובמקביל לכך כל הצעות המחיר 
ליד כל הצעת מחיר צריך להיות אייקנים שמתארים מהן אפשרויות תשלום הכסף של אותו ספק 
מזומן, שיק, העברה רגילה, העברת זה"ב, כרטיס נטען, העברה לצד ג',
העברה לחו"ל,
 מט"ח 

במקום עיר - שיכולה במקרים מסויימים להפליל ישר מי זה הספק - כי ברמלה למשל יש רק אחד 
וגם באשדוד
אז או שנוריד לגמרי את המיקום
או שנשים מרחק בק"מ ממיקום בית העסק..

ואז הטבלה תראה ככה:

: למעלה שם מושך השיק ופרטי השיק
מס' שיק, חשבון, בנק, מס' חשבון בנק

ולמטה טבלה אם סך השיק, התאריך מס' ימי ערך לשיק וסכומים נטו של הספקים השונים ואם נדרש להביא מסמך כלשהו
זהו.
ובצד כפתור של אשר עסקה
אחרי הכפתור הייתי מכניס את כל האמצעים לתשלום של הספק- שכן זה כביכל פחות קריטי מהסכום אבל גם חשוב וככה הכפתור לאישור נמצא במרכז השורה של ההצעה

**Comment by iddanh** [comment]
שכפול של סוגיות אחרות

**Comment by iddanh** [comment]
תוכל לפתוח סוגיה חדשה לגבי הסוגי תשלום?

ואת כל הפרטים האלה:
מס' שיק, חשבון, בנק, מס' חשבון בנק
לא ביקשנו בשום מקום...

**Comment by Sabanini** [comment]
עקרונית
המטרה הסופית היא שהמערכת תדע לקרוא לפחות את פרטי השיק המופיעים בתחתית
כך שזה החלק הקל יחסית..
כי בבר קוד
הקושי הוא בסכום ובתאריך

אז הוספתי את זה כדי שלא נשכח איפה זה חשוב להיכנס

אני אוסיף בלי קשר סוגיה




בתאריך 10 ביולי 2015 בשעה 13:48, מאת iddanh <notifications@github.com>:
