### ISSUE TITLE
 בעמוד שיקים חדשים ובכלל... אין צורך שהח.פ. של  המושך או ששם הלקוח יהיו בכחול יענו כלינק 

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#19]
הספק ילחץ איפה שהוא רוצה וכל לחיצה תוביל אותו לאן שצריך
הכחול מיותר
כי הרי גם יתר הטקסט מהווה לינק אז
אין באמת ייחוד ללינק המסומן בכחול

**Comment by iddanh** [comment]
אבל הלינקים האלה מובילים אותו לעמוד אחר מאשר אם הוא היה לוחץ במקום אחר בשורה
בלי הלינק איך הוא ידע את זה?

**Comment by Sabanini** [comment]
הןא ינסה פעם אחת ויבין
בתאריך 6 ביולי 2015 19:32,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
אני לא בטוח שזה רעיון טוב, זה יהיה מאוד מבלבל
חייבים איזה שהיא אינדיקציה
אולי ליד החפ לשים כפתור קטן עם אייקון של חץ או עין כדי לפתוח את עמוד לקוח \ מושך?
