### ISSUE TITLE
כשלוחצים על חלונית ח.פ. בלי מספר בה המערכת מקבלת תקלה

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#23]
שים לב שעדיין יש לקוחות או שיקים בלי ח.פ. וזה מוביל לתקלה

**Comment by iddanh** [comment]
כבר כתבתי בדיקה למצב הזה כדי שהמערכת לא תקרוס
וכבר אי אפשר לעלות שיק בלי לכתוב חפ
אז ברגע שננקה את המסד נתונים שלנו זה לא יקרה יותר
