### ISSUE TITLE
עמוד הצעות מחיר

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#24]
"יש לשנות את הכותרת העליונה שבאפור ל- "הצעות מחיר פתוחות
"ומתחת לכתוב: "להלן הצעות המחיר הזולות ביותר עבור השיקים שהועלו למערכת

הטבלה של השיקים שהתקבלו עליהם הצעות מחיר צריכות להכיל את העמודות הבאות בלבד:
שם המושך, ח.פ. המושך, מס' שיק, תאריך השיק, מס' ימי ערך, ערך נקוב, סכום נטו (בצבע ירוק), מסמכים נדרשים,  בהמשך השורה משמאל : כפתור - 'אשר הצעה', כפתור - 'צפה בכל ההצעות' (בצבע אחר

יש להוריד מהטבלה הזו את יתר הפרמטרים  

אחרי שלוחצים על 'צפה בכל ההצעות
 צריך לשים את 4 רכיבי השיק המלאים למעלה בשורה דקה כאשר הערך הנקוב מעל ההצעות נטו של הטבלה מטה
ומיד מתחתיו את הטבלה המפרטת את כל הפרמטרים של ההצעות השונות 
באופן הבא
דמי טיפול, ימי ערך, שיעור ריבית חודשית, סך ריבית, עמלת העברה, מע"מ, סכום נטו, מסמכים נדרשים, מרחק המציע
  בהמשך השורה משמאל : כפתור - 'אשר הצעה', 

את תמונת השיק יש לשים למטה

**Comment by iddanh** [comment]
לא ביקשנו מס' השיק כשמעלים שיק...
