### ISSUE TITLE
שינוי הכותרת מתחת לפרצוף

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#28]
מתחת לפרצוף הדמות שמופיעה מצד ימין בשני הצדדים - הלקוח והספק
כשהמערכת אומרת שלום
:היא צריכה להגיד
 " עידנוביץ' מערכות בע"מ "
אייל, שלום

**Comment by iddanh** [comment]
ברישום ספק לא ביקשנו שם הנציג
אז אני רק אומר לו "שלום ספק"
