### ISSUE TITLE
מרחק בין הלקוח לספק

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#31]
- [x] כשספק נרשם - יש לתת לו לבחור מה כתובתו מתוך רשימה סגורה
- [x] כשלקוח נרשם - יש לתת לו לבחור מה כתובתו מתוך רשימה סגורה

ככה אפשר להעשות רשימה של מרחקים בין כל מקום למקום
וכאשר הצעת מחיר ניתנת 
מוצג לצידה המרחק בין הלקוח לספק
בהפרשים של 5 ק"מ 
ככה הלקוח לא יוכל לדעת מי זה המציע עוד לפני שבחר בו

את הרשימה הזאת הייתי מנסה להוריד ממשרדים ממשלתיים או מיד 2 וכאלה
של כל הישובים בארץ
או מאטלס מעודכן

- [x] אני אחפש

**Comment by iddanh** [comment]
עשיתי יותר טוב אפילו
המשתמש מקליד וזה משלים לו את הכתובת בעזרת גוגל מפות!

את בדיקת המרחקים אני גם עושה דרך גוגל מפות אז זה בכי מדוייק ועדכני!
כמובן שאני אחר כך מוריד את הדיוק ל5קמ :)

**Comment by Sabanini** [comment]
אני אוהב אותך. עוד לא ראיתי אבל נשמע בנזונה
בתאריך 2 באוג׳ 2015 22:47,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
<3
