### ISSUE TITLE
סוגי תשלום

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#33]
- [ ] - צריך להוסיף בהגדרות של הלקוח כשהוא נרשם 
פירוט לאיך היה מעוניין לקבל את הכסף - 

מזומן, שיק, העברה רגילה, העברת זה"ב,

פתרון אחד להתמודד עם ריבוי הפשרויות תשלום הוא האופן הבא:
- [ ] - בעמוד הצעות מחיר בצד לקוח 
-תוצג עמודה אחת ששמה: 
עמלת תשלום
הסכום אשר יחוייב יצבע בצבעים שונים

למעלה נעשה מקרא 
שאומרת 
עמלת תשלום בהעברת זה"ב היא בכחול
עמלת תשלום בהעברה רגילה היא  בצהוב
עמלת תשלום במזומן הוא באדום
עמלת תשלום בשיק

וכך לקוח אשר מעוניין באמצעי הספציפי 
ידע שזה מה שעולה לקבל זאת

כלומר ייתכן שרק ספק אחד הציע הצעה 
לשיק ספציפי
אבל בגלל שהוא מסוגל לשלם לו במס דרכים
אז נולדות מספר הצעות מחיר  שונות
כאשר כל שורה מהווה תשלום באופן אחר

ככה הוא יוכל לברור מבין כל האפשרויות את זו שהכי מתאימה לו 
ובהתאם לאמצעי בו הוא רוצה את הכסף...

- [ ] - אצל הספק כשהוא ממלא הצעת מחיר גם בברירת מחדל שלו וגם בעמוד הצעת החיר עצמה צריך לתת לו יכולת לתמחר גם אמצעי תשלום שונים

אז אם ספק מלכתחילה קובע בברירת מחדל שאין לו אפשרויות מלבד העברת זה"ב 
שזה חלק מהספקים
אין מה לשנות בעמוד הצעת המחיר הספציפית לכל שיק

(כן צריך לאפשר לו לשנות זאת תוך כדי תנועה)

ספקים שמעדכנים בברירת מחדל שלהם פרמטרים אחרים מעבר להעברת זה"ב 
כמו אחוז פריטה במזומן (שזה למעשה שיעור עמלה הנגזר מהסכום המשולם נטו - אחרי כל העמלות האחרות) א

אז בעמוד הצעת מחיר קונקרטית צריך לאפשר לו לשנות זאת
וכך לגבי יתר האמצעים שעידכן שקיימים אצלו

**Comment by iddanh** [comment]
כל אמצעי תשלום יהיה הצעת מחיר חדשה?
לא עדיף שזה פשוט יהיה פרמטר של הצעת מחיר

**Comment by Sabanini** [comment]
גם אפשרות ואז אפשר לעשות מספר טבלאות כאשר כל אחת נותנת את תשלום שלה.. אבל
כשזה באחת עם צבעים שונים הוא יוכל לבחור מזו הכי זולה..

קח בחשבון שאנחנו בונים על לקוחות במובייל ככה שמס טבלאות יקשה עליו

אני מניח שאתה מתכוון לעמוד אחר לגמרי שבוא יפתחו רק ההצעות עם המזומן ועמןד
רק להעברות זהב..

אבל ככה יהיה לך קשה להשוות בינהן..
 בתאריך 10 ביולי 2015 15:49,‏ "iddanh" <notifications@github.com> כתב:

**Comment by Sabanini** [comment]
אני מכריע בסוגיה 
אם זה לא מורכב מידי
- [ ] לעשות מקרא צבעים עם שלושה צבעים בלבד כרגע
וכל אמצעי תשלום זו הצעה בפני עצמה
ככה הצעות של אותו ספק יתחרו אחת בשנייה כי אלה בעצם הצעות שונות
כי האמצעי תשלום שונה

הסיבה להכרעה היא כי הלקוח רואה בשלב הראשון רק את ההצעה הטובה ביותר 
ואז הוא גם יראה בגלל הצבע איזה אמצעי תשלום ניצח בהיתמחרות

אם מעניין אותו אמצעי תשלום אחר הוא יפתח את הרשימה המלאה ואז יבחר ממנה

ז"א שעדיף שכל אמצעי יהיה הצעה שונה

**Comment by iddanh** [comment]
הוחלף עם #76
