### ISSUE TITLE
כתובת הספק בהצעת מחיר

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#39]
![2](https://cloud.githubusercontent.com/assets/13170174/8621978/4c2abbfc-2731-11e5-9eda-5a5da37f301f.JPG)
ברשימת הצעות המחיר 
פתאום רואים את כתובת הספק

זה ספק חדש שפתחתי

**Comment by iddanh** [comment]
כרגע שמתי את כתובת הספק עד שאני אוסיף את הפיצר של מרחק
