### ISSUE TITLE
מערכת חדשה להמרת מטבע חוץ - רק אחרי שמסיימים הכל

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#44]
## מעמוד הנחיתה אחרי שלוחצים על המרת מט"ח מגיעים לכאן

- [x] צריך ליצור פלטפורמה בה
לקוח רושם סכום של כסף אותו הוא רוצה להחליף ולצידו את סוג המטבע
צריך להיות מעין משפט כזה עם חלוניות בתוכו שהלקוח ממלא בסגנון של
יש לי #סוג המטבע בסכום כולל של # חלונית 
ואני מעוניין להחליף אותו ל#מטבע מסוג
או
כותרת: הכסף שיש ברשותי
בה הוא מכניס את הסכום שהוא מעוניין להחליף
ויש ליד חלונית הסכום
חץ למטה עם רשימת מטבעות סגורה

המטבע אותו ארצה לקבל בתמורה
חץ למטה הפותח רשימה סגורה של מטבעות
 - [x] 'כפתור: 'שלח בקשת המרה

## בצד הספק
צריך להקים דש בורד לספקי המרת מט"ח

### בעמוד ההגדרות מחדל
- [x] צריך לתת לו אופציה המאפשרת לו לבחור מתוך שתי רשימות 
הראשונה היא מטבעות אותם הוא מוכר 
- [x] הרשימה השניה - מטבעות אותם הוא מוכן לקנות

הפיצ'ר הזה יהיה כך: 

ליד כל מטבע ריבוע קטן אותו הוא צריך לסמן
כי יכולים להיות מספר מטבעות
כך כאשר לקוח מבקש לדוגמא 
למכור יורו ולקנות 
לירה מיצרית
המערכת צריכה לוודא כי הצ'יינג' 
באמת מחזיק לירה מיצרית
ושהוא יודע לקנות יורו
בוא נתחיל עם הרשימה הבאה
![image](https://cloud.githubusercontent.com/assets/13170174/9291238/dbde5a4a-43bc-11e5-8129-9c8c96dca17c.png)

עדיין בעמוד הגדרות המחדל צריך להיות הדבר הבא:
אופן התמחור של הספק
שישפיע על האופן שבו המחשבון יחשב

ז"א שצריך לתת לספק לבחור מבין שתי האופציות  ע"י צ'ק בוקס קטן בתחילת כל אופציית תמחור
כאשר הוא לוחץ על האופציה הרצויה ככה יופיע לו המחשבון בעמוד הצעות המחיר  

## אופציה ראשונה
לאפשר לו להמיר את הסכום הנדרש בשער מטבע אחד כאשר השער כבר כולל את העמלה של הצ''ינג
'נקרא לאופציה זו 'שער חליפין בלבד
זו צריכה להיות גם ברירת המחדל

## אופציה שניה 
לתת שער חליפין - לסכום שמביא לתוצאה של החלפה 
ואז להוסיף את עמלת הצ'יינג'
שכמובן שתפחית את הסכום לתשלום
במחשבון צריך לתת לזה ביטוי

## הפעלת המנגנון
צריך ליצור בצד הספק עמוד חדש שקוראים לו עמוד בקשות להמרת מט"ח 

כאשר ספק מקבל בקשה חדשה להמרה והוא לוחץ עליה
נפתח לו עמוד בו מופיע הסכום הנדרש והמטבע שהוא נמצא בו והמטבע בו מעוניין הלקוח

- [ ] בסיום הזנת פרטי ההצעה
צריך שיהיה לו מקום 
להכניס עד איזו שעה ותאריך ההצעה תקפה

## בצד הלקוח
לאחר  שקיבל מס' הצעות מחיר
צריך להיות מוצג
- [x] הסכום נטו אותו הוא מעוניין לקנות
בניכוי העמלות

ובסוף הרשימה
- [x] עד איזו שעה ההצעה תקפה

זאת אומרת שמבחינת הלקוח הוא רואה מספר הצעות אחת מתחת לשניה - כמו השיקים
כאשר הזולה ביותר- זו שמביאה סכום גדול יותר ראשונה

ולאחר מכן בטבלה גם, את הזמן הנותר למימוש ההצעה
ומרחק הספק ממקום הלקוח
ברגע שעסקה פגה תוקף, היא צריכה לרדת לסוף הרשימה עדיין להופיע אבל להיות סגורה לאישור, בתוספת ההצעה בטלה הזמן עבר
זה כדי להאיץ בהם פעם הבאה לאשר מהר

באותה צורה של השיקים הלקוח מאשר את ההצעה
היא עוברת לעסקאות מאושרות
אצל הלקוח זה למעקב ביצוע
נחשף שם הצ''ינג' שמו וכתובתו
אחרי שהעסקה מסתיימת מעבירים אותה לעסקאות שבוצעו
עם כל הכפתורים הקיימים

**Comment by iddanh** [comment]
איזה מט"ח להציע?
תן לי רשימה

**Comment by Sabanini** [comment]
http://www.boi.org.il/he/Mobile/Pages/ExchangeRates.aspx
בתאריך 18 באוג׳ 2015 22:37,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
אז באופציה הראשונה הספק צריך לכתוב את יחס ההחלפה ותוספת עמלה ואני מחשב את הסכום הסופי
בעוד שבאוצפיה השניה הוא רושם את הסכום הסופי ואת העמלה ואני מחשב את יחס ההחלפה?

הבנתי נכון?

וגם איך לקרוא לאופציה השניה?

**Comment by Sabanini** [comment]
לא
באופציה אחת הוא שם שיעור המרה ולטוטל מוסיף עמלה.

באופציה השניה הוא שם שיעור המרה וזהו..
יוצא שבשניה העמלה שלו כבר בפנים כי השיעור המרה פחות טוב

לדוגמא נניח שבא מישהו להחליף 1,000 דולר ושער בדולר היציג 3.87 אז באופציה
השניה הוא ימיר לך את הכסף ב3.84 וירוויח 30 שקל.  כי במקום שייתן 3,870 שח
הוא יתן לך 3,840 שח.

בעוג שבאופציה עם העמלה השיעור המרה שלו הוא 3.87 ואז הוא מוסיף עמלה שמקטינה
את הטוטל שאתה מקבל לדוגמא 35 שח אז תקבל 3,835 ש"ח
בתאריך 24 באוג׳ 2015 21:02,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
הבנתי

**Comment by iddanh** [comment]
למה צריך להפריד את שני השיטות?
אני יכול לתת לו תמיד אפשרות להכניס עמלה ואם הוא רוצה שישאיר אותה אפס פשוט
לא?

**Comment by Sabanini** [comment]
אתה צודק. ואתה גאון
רק תדווא שברירת המחדל היא אפס
בתאריך 25 באוג׳ 2015 20:04,‏ "iddanh" <notifications@github.com> כתב:
