### ISSUE TITLE
עמוד הצעת מחיר פתוחות

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#46]
בגירסת המובייל בטוח

צריך להוריד את העמודות הבאות
ימי ערך
(ח.פ. מושך (הלקוח מכיר את השיקים שלו

אפשר גם להוריד את הכפתור צפה בכל ההצעות
כי לחיצה לא על הכפתור אשר  הצעה
בכל מקרה מעביר אותו ליתר ההצעות
כך שהכפתור מיותר

**Comment by iddanh** [comment]
להוריד את זה גם בדסקטופ או רק למובייל?

**Comment by Sabanini** [comment]
בדסקטופ אפשר להשאיר כי אנחנו נציג את המערכת עליו

במובייל זה בטוח מיותר
