### ISSUE TITLE
 העלאת קבוצה של שיקים- מסקנות אחרי שיחה משותפת

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#51]
עמוד הצעות מחיר בצד הלקוח יראה באופן הבא:
- [x] כל השיקים שלקוח העלה וקיבלו הצעות מחיר כלשהן יופיעו בעמוד הצעות מחיר כשיש לצידן ריבוע צ'ק בוקס קטן מימין
ברירת המחדל היא שכל השיקים יסומנו  בצ'ק בוקס
המצב הנ"ל יתקיים אם קיים ספק שאכן אישר את כל השיקים שהועלו
באופן  אוטומטי יופיע הנטו של כל קבוצת השיקים 
כאשר לצורך החישוב עמלת התשלום/העברה יפחית מהנטו פעם אחת - כלומר את התשלום של הסכום נטו הספק משלם פעם אחת ולכן יש לחשבו פעם אחת בלבד
מיד מתחת לנטו הטוב ביותר שהוצע על אותה קבוצת שיקים
יוצגו כל יתר הסכומים נטו שהוצעו על ידי ספקים אחרים על אותה קבוצה מהנטו הגבוה ביותר (העמלה הזולה ביותר) ואילך

אבל!!!
- [x] היה ואין ספק אחד שאישר את כל השיקים שהועלו
אבל כל השיקים כן קיבלו הצעת מחיר מסויימת
 המערכת תסמן אוטומטית כבר בפתיחת העמוד את הקבוצה הגדולה ביותר שכן אושרה על ידי ספק אחד, (במונחי ערך השיקים ולא מס' השיקים) ויוצג הנטו הכי טוב שהוצע 
גם במקרה כזה 
מיד מתחת לנטו הטוב ביותר שהוצע על אותה קבוצת שיקים
יוצגו כל יתר הסכומים נטו שהוצעו על ידי ספקים אחרים על אותה קבוצה מהנטו הגבוה ביותר (העמלה הזולה ביותר) ואילך

- [x] לצד כל סכום נטו שיוצג יופיע המרחק מהספק שהציע ההצעה
כדי לאפשר ללקוח לבחור את הספק הקרוב ביותר למקום עסקו

- [x] הפרטים אשר יוצגו בעמוד הזה הם כדלקמן:
שם המושך, תאריך השיק, סכום השיק, מסמכים נוספים, ולבסוף סכום נטו אשר יסוכם לנטו אחד שממנו תופחת עמלת אמצעי התשלום

(הורדתי פה את ח.פ. המושך, ואת ימי הערך שפחות חשובים)

- [x] השיקים שלא אושרו במסגרת הקבוצה הגדולה ביותר, יוצגו בהמשך העמוד (מתחת לטבלאות הקבוצה) עם הפרטים שצויינו בסעיף הקודם בלבד, כאשר להם יוצמד הנטו הספציפי שלהם

- [x] כל פעם שיוסר סימון משיק המופיע בקבוצה באופן אקטיבי על ידי לקוח, תיוולד הצגת קבוצה חדשה ואותו שיק שהוסר ממנו הסימון יועבר לתחתית העמוד ותוצג ההצעה הטובה ביותר שניתנה לו כשיק בודד 
(באופן זהה למה שהיה עד עכשיו)

- [x] מה קורה כאשר לוחצים על קבוצת שיקים ספיציפית
במידה ולקוח מעוניין לדעת מה הם הפרמטרים הספציפים של הצעת המחיר שהוצעו לקבוצת שיקים 
הוא ילחץ עליה ויפתח לו עמוד, בו יפורטו כל הפרמטרים של ההצעה
הכוללת גם את ימי הערך (במס' אחד - הכולל את הימים שבשיק בצירוף, תוספת ימי הערך שהספק הוסיף), עמלת טיפול שיעור הריבית החודשית, וסך הריבית (בכסף) ועמלת אופן התשלום לכל הקבוצה 

- [x] מכיוון שכעת אנחנו מסתכלים על קבוצה ספציפית שספק אחד הציע עליה, יוצגו כל אמצעי התשלום שאותו ספק מסוגל לשלם 
וליד כל אמצעי תשלום, יופיע הנטו הנגזר מאותו אמצעי - עם סמל או טקסט
לדוגמא 
102,500 - שיק
102,340 - מזומן
102,300 - העברת רגילה
102,285 - העברת זה"ב

- [x] כאשר לוחצים על שיק בודד, אשר קיבל הצעת מחיר אבל לא נכנס לקבוצה ומופיע לצידו הנטו הטוב ביותר
יפתח עמוד, ובו כל יתר הצעות המחיר שהוא קיבל
כשליצדן המרחקים מהספקים שהציעו עליו הצעה

כמו מה שהיה עד עכשיו

- [x] צריך להשאיר את כפתור אשר הצעה - אבל אפשר להוריד את צפה בכל ההצעות
הלקוח יוכל פשוט ללחוץ על הנטו ולעבור ליתר ההצעות מחיר של אותה קבוצת שיקים או שיק ספציפי 
/בודד

- [x] אחרי שלקוח בוחר את השיקים ולוחץ על כפתור הצג הצעה משותפת על השיקים שנבחרו
ומופיעה לו התוצאה - 
צריך למקם כפתור זמין שמחזיר אותו לעמוד הקודם, 

 בהצלחה!!!!!

**Comment by iddanh** [comment]
לגבי הנקודה האחרונה:
כפתור החזור של הדפדפן יחזיר אותו לסימון הקודם שהיה לו

**Comment by Sabanini** [comment]
הכוונה היא אחרת
אסביר
סביבת העבודה העיקרת בבחירת הספק המתאים היא לא בעמוד הראשון שעולה כשלוחצים על עמוד הצעות מחיר
אלא בעמוד השני שעולה כשולחצים על הקבוצה הרצויה

שם רואה הלקוח את כל הפרטים העסיסיים
כמה ספקים הצעו כמה כל אחד נותן וכדומה
וגם פה חייב שיהיה ללקוח אפשרות לשנות את הרכב הקבוצה שאותה הוא בוחן 
זא שצריך למקם לו כפתור גם בעמוד הזה של 
הצג הצעה משותפת לשיקים שנבחרו

כי אם בעמוד הזה שבו רואים את כל ההצעות המפורטות של כל הספקים, החליט הלקוח לשנות את הרכב הקבוצה צריך שיהיה לו כפתור לכך
תוצאת הלחיצה צריכה להחזיר אותו לעמוד הראשון בו הוא רואה את ההצעה הטובה ביותר עבור הקבוצה החדשה שלחץ ללא השיקים שביטל סימונם..

מפה הוא כמובן יוכל ללחוץ שוב על הקבוצה כדי לראות את כל ההצעות שניתנו עי הספקים השונים..

**Comment by iddanh** [comment]
אם הבנתי נכון אז במקרה הזה הוא ילחץ על הלינק הצעות שהתקבלו בתפריט בצד ימין וזה יחזיר אותו לעמוד שהוא רוצה

**Comment by Sabanini** [comment]
לא

**Comment by iddanh** [comment]
### בעמוד מפורט של קבוצת שיקים
כותרת: ספק ואז מספר
השיקים עצמם עם צ'ק בוקס שמסומן בהתחלה
טבלת סך הכל
כפתור אשר הצעה שמאשר רק את מה שמסומן באותו קבוצה
כפתור חשב מחדש שמחזיר הצעה חדשה של מה שסומן

זה יהיה זהה לכל ההצעות לא רק הכי טובה
כלומר בכולם יהיו צ'ק בוקסים

נשמע טוב?

**Comment by Sabanini** [comment]
תוסיף כפתור חזור לרשימה המלאה
כדי שתהיה אפשרות להוסיף שיקים שהוסרו

ושים לב לצמצום העיצובי 
בדומה למה ששלחתי לך

**Comment by Sabanini** [comment]
#לא לשכוח מרחק מספק

**Comment by iddanh** [comment]
סבבה עיצוב עשיתי רק עוד לא העלתי
מרחק מספק וסוגי תשלום אני אוסיף הם סוגיות משל עצמם

**Comment by Sabanini** [comment]
### מלך אתה!
