### ISSUE TITLE
הערת עיצוב קטנה לסרגל הימני

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#52]
כל הכותרות צריכות מסוגננות כך שהן בשורה אחת ושהאורך שלהם לא מפצל אותן לשתי שורות

זה פוגע באסטטיות

אם לא מסתדר לך דבר איתי ונחשוב על משפט קצר יותר

או שנרחיב טיפל'ה את הסרגל

**Comment by iddanh** [comment]
יש כמה אופציות: 
* לשנות את הטקסט למשהו קצר יותר
* להקטין את הפונט
* להרחיב את הסרגל

 איזה דפ"א  אתה רוצה?

**Comment by Sabanini** [comment]
קודם כל תשנה את שמות העמודים אצלך לשמות שלהם בעברית
כך שאם שמים עליהם את העכבר מופיע שמם המלא

שנית - לדעתי כרגע חוץ מעמוד שיקים ללא הצעת מחיר שאותו יש לשנות ל-
שיקים ללא הצעה
וכך הוא יהפוך לשורה אחת

אני חושב שהסרגל הימיני סבבה


בעתיד 
יהיו רק אייקונים בברירת מחדל של האפליקציה ממבט הלקוח, ואם הוא ירצה לקרוא את כותרתן הוא יפתח אותו באמצעות לחיצה על כפתור השורות

אבל בשוטף שלו הוא כבר יכיר את הסמלים וככה אנחנו מקבלים תצוגה רחבה יותר לעבודה..
