### ISSUE TITLE
סגירת קבוצת עסקאות מאושרות

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#54]
- [x] הכי חשוב - להוסיף כפתור אישור הצעה - הרי מטרת איחוד השיקים הם כדי לאפשר ללקוח לאשר הצעה מיטבית, שהתקבלה מספק אחד, מבלי שהוא יודע מיהו עד שהוא מאשר ההצעה, 
לכן צריך להוסיף כפתור אישור

לאחר שלוחצים על הצעה מאוחדת עוברים לעמוד המשך בו מפורטים יותר פרטים לגבי העסקה
פה למעשה צריכים להופיע כל הספקים שהציע הצעות על השיקים שסומנו
ז"א שצריך לתת להם מקום..
בנוסף בהתאם לסעיף הראשון, צריך להכניס גם לעמוד הזה כפתור אישור הצעה..
וכדי לתת מקום ולהציג את מס' ההצעות מחיר השונות 

 - צריך להוריד לשורת הסה"כ 
- [x] את הכותרת ספק#1 

ומיד מתחת לסה"כ הראשון
יופיע ספק#2 עם הצעת המחיר שלו
וכן הלאה

- [x]  בשורת הסה"כ מופיעה עמלה - לדעתי היא משקפת חישוב הסכום של כל העמלות שניתנו על כל השיקים והיא צריכה להיות פעם אחת על כל העסקה

- [x] באופן כללי הביטוי ספק #1 וספק#2 וספק#3 - נראיה טוב, והייתי מוסיף את זה לכל המקומות בהם ישנן הצעות מפורטות מספקים שונים- זה עושה שכל ומסביר בצורה מעולה מה אנחנו רוצים מהחיים של הלקוח...
ראיתי שעשית את זה - טוב מאוד!!!

- [x] שורת הסה"כ בהצעות מחיר - לעיתים בגלל שינויי רזולוציה - נהפך להיות טבלאונת קטנה ולא יפה משמאל

- [x]  לא תמיד כשלוחצים על כפתור הצעות מחיר שנמצא בסרגל מימין, כבר בפתיחת העמוד הראשון הקבוצה לא מסומנת..
אני מניח שזה כרגע במקרים בהם לא כל הקבוצה אושרה על ידי ספק אחד..
במקרה כזה, צריך שהקבוצה שכן אושרה על ידי אותו ספק, עם הסכום כסף הגדול ביותר, תהיה מסומנת ומשם הלקוח יתחיל מלאכתו בבחירת הספק המתאים ביותר

אבל מצב בו אף שיק לא מסומן זה מצב מיותר כי מיד אחריו הלקוח יצטרך לעשות עבודה במקום שהמערכת תעשה לו את זה אוטומטית..

- [x] לאחשר שאתה מכניס את הכפתור אשר הצעה זה אומר שקבוצת השיקים שאושרה צרכיה לעבור לעמוד עסקאות מאושרות - כלומר לביצוע על ידי הלקוח
בעמוד הזה יופיע פרטי הספק שהציע ההצעה לכלל השיקים החברים בקבוצה, 
חשוב שם, ליצור הפרדה בין השיקים שבקבוצה שאושרו ע"י ספק אחד
ויתר השיקים שאושרו באופן פרטני ע"י הספק הנבחר שלהם...

עניין אחר טכני - באגי
- [x] כאשר קבוצה מסויימת נבחרה ע"י לקוח ויש על כולם הצעות מחיר
ויש עוד שיקים שלא נבחרו ומופיעים מטה.

כאשר מוסיפים עוד שיק כדי לראות אם גם הוא אושר על ידי אותו ספק, 
ואז לוחצים על הכפתור - הצג הצעה משותפת לשיקים המסומנים
אם אותו שיק לא אושר על ידי אותו ספק זול, או היחידי שהציע על כל יתר השיקים שנבחרו
המערכת מאפסת את כל הבחירה שנעשתה עד עכשיו ומסירה את הבחירה מכל הריבועים,
וזה לא טוב!!

היא צריכה להשאיר את כל הריבועים מסומנים, ופשוט להודיע, כי השיק הנוסף לא אושר במסגרת הקבוצה שנבחרה

חשוב להבין כי אם יבחר את השיק הזה עם שיק אחר
ייתכן וכן תעלה לו הצעה, הרי השיק שמופיע מטה מחוץ לקבוצה עדיין קיבל הצעת מחיר, אבל ייתכן כי הספק שאישר אותו לא אישר משום מה אף שיק אחר 
או שאישר נאמר רק שיק אחד, אז המערכת צריכה להמליץ לו לבדוק אופציות אחרות...
זה לא קריטי כרגע...

**Comment by iddanh** [comment]
* לא הבנתי את נקודה 2
* איזה מידע להציג בטבלה סה"כ לכל קבוצת שיק?

 כרגע זה רק סה"כ ערך נקוב וסה"כ לתשלום

**Comment by iddanh** [comment]
בעמוד עסקאות מאושרות בצד לקוח, בקבוצת שיקים אני צריך לשאול על כל שיק בנפרד איך בוצעה או כולם כקבוצה?

**Comment by Sabanini** [comment]
לגבי נק' 2 זה בסדר הסעיף כבר קיים,
 הכוונה הייתה לשים כותרת של מס' הספק

המידע שצריך להציג בטבלה של סה"כ קבוצת השיקים:

קודם כל אם אתה יכול לצמצם משמעותית את רוחב השורה של הכותרת סה"כ אז זה יהיה מדהים 
השאיפה היא שהלקוח יוכל לראות כמה שיותר הצעות שונות באותו עמוד..

לצורך העניין 
שורת הסה"כ בכלל לא צריכה לבלוט מתחת לטבלה הקיימת אלה להיות לצד סכומי הסה"כ 
כך שלא "יתבזבז" מקום בתצוגה
(שמתי לך תמונה לדוגמא: (המידע שצריך להופיע זה רק הברוטו הנטו ועמלת העברה
הנטו של כל הקבוצה צריך להיות גם בירוק ואפילו הייתי עושה אותו בבולט או אישכהו שונה מיתר הירוקים של כל שיק ושיק
![default](https://cloud.githubusercontent.com/assets/13170174/8808897/f6155d10-2fed-11e5-8769-7ce95bc713dc.jpg)

**Comment by Sabanini** [comment]
לגבי עמוד עסקאות מאושרות
הייתי שם גם שם ריבועים מימין שמסמנים את השיקים 
וכפתור אחד משמאל 
ככה שיכול לקוח לסמן את כולם וללחוץ העסקה בוצעה

ואז הוא יכול בפעם אחת לדווח על כל השיקים ולחסוך לחיצות
אם העסקה בוצעה בתנאים שונים
הוא יצטרך ללחוץ על שיק ספציפי שבוצעה בתנאים שונים או שלא בוצע
ולמלא את המשוב המלא
ז"א אומרת שהוא סימן שיק ספציפי בריבוע הקטן מימין ואז לחץ על אחד משלושת הכפתורים
בוצע בוצע בתנאים אחרים או לא בוצע

אז לסיכום בעמוד עסקאות מאושרות יש ריבועים מימין לשיקים ושלושה כפתורים מתחת לכולם אשר מתיחסים לשיקים שנבחרו,

ברירת המחדל צריכה להיות כשפותחים את העמוד הזה היא שכל השיקים לחוצים מימין
כדי שהלקוח יוכל בפעם אחת לדווח
ולא שיק שיק

תגיד לי אם יש בעיה טכנולוגית לבצע זאת

אני חושב שזה הכי יעיל כרגע
צריך להיות את הכפתורים שמתייחס לכל הקבוצה 
כאשר יש בצד ריבוע צ'ק ליסט
ואפש

**Comment by iddanh** [comment]
איך זה יעבוד אם כמה שיקים בוצעו בתנאים אחרים?
צריך לשאול עבור כל שיק מה קרה באמת
זה קצת בעייתי

**Comment by Sabanini** [comment]
הרי הלקוח יכול לענות בכל מקרה מה שהוא רוצה נכון?

ואם אנחנו יוצאים מנק' הנחנה שהוא לא משקר
אז אנחנו צריכים להקל לו על החיים שגם ככה מסובכים כי הוא חייב לתת לנו משוב
שדרך אגב עצם העניין הזה עדיין תחת בדיקה אם יעיל או לא

זא שבאופציה שהצעתי
אותו לקוח יכול לסמן שיק ספציפי וללחוץ על הצעה שונה 

אבל אם העלה 10 שיקים וכולם בוצעו ובאותם תנאים אז למה לבקש ממנו לאשר שיק שיק
הוא מסמן את כולם ולוחץ

או שיותר טוב הם כבר כולם מסומנים לו
אז הוא רק מוריד את זה שלא בוצע ומאשר את היתר
או מבטל סימון בשניים שבוצעו בתנאים שונים מאשר את כל היתר
ואז מסמן אחד אחד ומעדכן את פרטי העסקה החדשים

**Comment by iddanh** [comment]
אז במקרה של שהעסקה בוצעה או לא בוצעה זה קל. 
במקרה שהעסקה בוצעה בתנאים אחרים זה החלק הבעייתי. איך אני עובר משיק לשיק? כי פה אני כן צריך לשאול על כל שיק

**Comment by Sabanini** [comment]
אז עדיין מופיעים שלושת הכפתורים פעם אחת בלבד
והם יתיחסו רק לשיקים שסומנו

ז"א שאם יש שיק שבוצע בתנאים אחרים
אז אחרי שהלקוח סיים לדווח לי על השיקים שבוצעו במדוייק הם מסמנים רק שיק אחד ומדווחים על עסקה אחרת

**Comment by iddanh** [comment]
סבבה, אז רק לוודא: 
להגיד שעסקה עברה או לא יהיה ניתן לעשות כקבוצה. 
אבל לעדכן את העסקה יצטרף לעשות שיק שיק

**Comment by Sabanini** [comment]
חיובי,

**Comment by iddanh** [comment]
הוספתי סוגיה #81
