### ISSUE TITLE
"חשוב חשוב! כאשר לקוח מאשר הצעת מחיר של קבוצת שיקים - להעביר אותו לעמוד "האם אתה בטוח

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#57]
לקוחות חדשים לא בהכרח מבינים את המשמעות של לאשר עסקה
'לכן כאשר הם מתנסים באפליקציה - לחיצה על כפתור 'אשר עסקה 
מחייבת אותם ומעיפה להם את השיקים מהצעות מחיר לעסקאות מאושרות ומשם אין דרך חזרה!!!

"?לכן צריך לפתוח להם "עמוד האם אתה בטוח

לפני כן כאשר היו רק שיקים בודדים שמת את השיק ושאלת, כעת כאשר מדובר על קבוצת שיקים, עדיין צריך לשים להם את כל העסקה המפורטת 
ולשאול אותם האם הם בטוחים, ללא תמונה רק טבלה 
עם הפרמטרים הבאים:

  שם המושך, תאריך, ימי ערך, סכום הריבית בלבד , ע.נקוב, , 
מתחת לכל הערך הנקוב
סה"כ ע.נקוב
מתחת לכך את סכום כל העמלות יחד כולל עמלת העברה
סה"כ לתשלום

מימין יתר העמלות כמו בתמונה 

![default](https://cloud.githubusercontent.com/assets/13170174/8833482/8deb1cb4-30b7-11e5-9800-580473a9a076.png)

"בנוסף למעלה בעמוד "האם אתה בטוח
צריך להוסיף את הטקסט הבא
לחיצה על אישור תחשוף בפניך את זהות חברת הניכיון, כתובתה ופרטיה, פעולה זו אינה ניתנת לביטול  
לחץ רק אם אתה בטוח בעסקה

**Comment by iddanh** [comment]
מה זה ע. נכיון וע. תשלומים במונחים שאני מכיר?
וד.גבייה זה עמלת העברה?

**Comment by Sabanini** [comment]
ע.ניכיון זה סך הריבית
דמי גביה זה דמי טיפול
ע.תשלומים זה עמלת העברה
עמלות זה הסה"כ של כל הרכיבים הנ"ל

**Comment by iddanh** [comment]
סבבה
אתה רוצה שהכותרות יהיו כמו בתמונה או במונחים שלנו?

**Comment by Sabanini** [comment]
וכשיש מספר שיקים כל רובריקה  מסכמת את סוג העמלה המסויימת לכלל השיקים

והסה"כ עמלות הוא הסה"כ של כל הסה"כולים

**Comment by Sabanini** [comment]
תשאיר כמו שלנו כרגע כדי לא לשגע פילים
אחרי זה נראה את הכל כמכלול ונחליט
זה פחות קריטי כרגע
