### ISSUE TITLE
בעמוד עסקאות מאושרות בצד לקוח

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#63]
פה צריך להציג את השיקים שהלקוח אישר את הצעת המחיר שלהם
והיה אמור להגיע איתם לחברת הניכיון לביצוע בפועל
בנוסף לפרטים שמופיעים כרגע 
- [x] חשוב שבטבלה יופיעו כל הפרטים של הספק: שם העסק, כתובתו, מספרי טלפון ומרחק מהלקוח 
אם יש בעיה של מקום בשורה אפשר להוריד את הח.פ. של המושך

- [ ] כל השיקים צריכים להיות בטבלה אחת כאשר יש לכל שיק צ'ק בוקס משמאל
ללא קשר לעובדה שאושרו כקבוצה או לא
זא כמו הרשימה התחתונה הקיימת כרגע עם הכחול הכהה יותר- זה טוב

- [ ] מה שכן אם אפשר יהיה זה לצבוע בצבע עדין את הרקע של השיקים שאושרו מול אותו ספק או את המסגרת של הטבלה להקל על הלקוח בזיהוי שלהם 

- [ ] מעל הטבלה צריך למקם את שלושת הכפתורים
העסקה בוצעה
בוצעה בתנאים שונים
העסקה בוטלה

וכך על הלקוח לסמן שיקים בצ'ק בוקס וללחוץ מה קרה איתם
בשאיפה שיסמן את כולם בעסקה בוצעה
לכן  
- [ ] ברירת המחדל צריכה להיות שכל השיקים מסומנים 

אם אפשר כשהוא לוחץ על יותר משיק אחד 
'כפתור 'בוצעה בתנאים אחרים 
צריך להעלם או להיות לא פעיל

אלא אם אתה חושב שאפשר לתת לו להשיב על פרטי העסקה של כל שיק ושיק ברצף
בעמוד המחשבון עד שיסיים את המשוב על שינוי הפרטים שבוצעו

אני אישית לא אוהב את הכפתור הזה ויכול להיות שנוריד אותו בעתיד אבל כרגע עשית עבודה טובה איתו 

אז קבל החלטה לגבי אם לנטרל אותו בבחירה מרובה 
או להעביר את הבחירה המרובה לעמוד מחשבון שבסיומו נפתח עמוד מחשבון נוסף עד שמסיימים את כל רשימת השיקים שנבחרה

זה המצב כרגע 

![image](https://cloud.githubusercontent.com/assets/13170174/8891181/be92699a-3327-11e5-8a46-9545fda70962.png)

**Comment by iddanh** [comment]
הוספתי סוגיה #81
