### ISSUE TITLE
בעמוד הצעות מחיר- העלמת עמודת מסמכים נוספים

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#67]
בחלק מהמגמה שלנו לחסוך במקום בטבלאות המוצגות ללקוח כי הוא צופה במובייל
אחת האפשרויות לחסוך בשטח התצוגה יכולה להיות כאשר ישנו מצב בו 
קיימת טבלה בה מוצגים שיקים ובאף אחד מהם אין דרישת מסמכים נוספים

במקרה כזה יש להעלים את העמודה כולה

הדבר יחסוך משמעותית במקום
וכנראה שהדרישה הזו תהיה במקרים בודדים

**Comment by Sabanini** [comment]
זה לא תוקן
עדיין יש את  התופעה

**Comment by iddanh** [comment]
פשוט לא עשיתי את זה על כל העמודים

**Comment by Sabanini** [comment]
🔥 אתה
בתאריך 9 באוג׳ 2015 20:40,‏ "iddanh" <notifications@github.com> כתב:
