### ISSUE TITLE
- ריבית אפקטיבית חשוב מאוד מאוט - ודחוף בעמוד הצעות מחיר

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#68]
בעמוד הצעות מחיר - נכון לעכשיו כל לקוח רואה קבוצת שיקים שכולם קיבלו הצעת מחיר
והוא רואה את ההצעה הזולה ביותר מבחינתו
אם הוא מסיר שיק או שניים מהרשימה הנבדקת הוא מקבל תוצאה חדשה כאשר השיקים שהוא הוריד מופיעים בחלק התחתון ולגבי השיקים שבחר הוא מקבל את התוצאה הטובה ביותר

אבל, אין לו אפשרות לדעת האם הסרת השיקים הנ"ל שיפרו לו את המצב או לא..
הדרך היחידה שלו לדעת האם שיפר מצבו זה ע"י בדיקת הריבית על שיק ספציפי מתוך הקבוצה הראשונה בהשוואה לאותו שיק במסגרת הרשימה הקטנה יותר

לכן צריך להוסיף פיצ'ר חדש בטבלה הזו עוד בשלב הראשוני - של ההצעה הטובה ביותר 
הפיצ'ר ישקף ללקוח את המחיר הממוצע של אותה עסקה חדשה שבחר ומבצע עליה בדיקת מחירים..
הפיצ'ר הזה הוא ריבית אפקטיבית 
אשר תופיע לו יחד עם הטבלה, בשאיפה בחלקה העליון ולא איפה שהנטו
בהמשך כאשר הוא יבחן את כל ההצעות שניתנו לו ע"י הספקים ע"י לחיצה על הטבלה..
תופיע לו הריבית האפקטיבית בראש כל טבלה, לגבי כל ספק וספק

אז איך מחשבים אותה
מדובר על הממוצע המשוקלל של הריביות האפקטיביות של כל עסקה ברשימה שנבחרה 
חישוב הריבית האפקטיבית 

מתבצע ע"י חילוק ההפרש בין הברוטו לנטו
בברוטו
זה נותן לנו ריבית אפקטיבית כללית 
לדוגמא 
אם על שיק של 105,000 ש"ח ירד 4,356 ש"ח עמלות וריבית
4356/105,000=0.0414 -> 4.14%
0.0414*(ימי הערך כולל התוספת) / 
30= הריבית האפקטיבית החודשית
שצריכה להיות מוצגת באחוזים

לידה תוסיף את התוצאה שיצאה לך - הריבית האפקטיבית החודשית כפול 12 כדי שתוצג גם הריבית השנתית

עכשיו לוקחים את הריביות האפקטיביות של כל השיקים ועושים להם ממוצע משוקלל
 כלומר מכפילים את כל שיעורי הריביות האפקטיביות בסכומי הסה"כ עמלות ומחברים את כל התוצאות ואז ומחלקים את  התוצאה לסכום כל העמלות שיצאו
התוצאה אמורה לתת את הריבית האפקטיבית החודשית המשוקללת
הממוצעת

בחישוב הנ"ל צריך לשים לב לעמלת העברה
אם מדובר בשיק בודד עמלת העברה היא אחת לגבי אותו השיק, אז בחישוב יש להכליל אותו בסה"כ עמלה שמשולמת

במקרה של קבוצה יש לחשב את עלות התשלום פעם אחת בלבד בנוגע לכל הקבוצה

עכשיו ברגע שלקוח יכול לראות מה היתה הריבית הממוצעת המשוקללת האפקטיבית שקיבל על קבוצת שיקים ספציפית, הוא יכול לעשות מס' השוואות 
ותמיד לקבל לגביה את הריבית הממוצעת האפקטיבית שלהם

**Comment by iddanh** [comment]
העברתי חלק ממה שכתבת לסוגיה חדשה
