### ISSUE TITLE
בעיית תצוגה בעמוד למעקב ביצוע

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#71]
צריך להציג את השיקים בלמעקב ביצוע שהיו בקבוצה, אחד אחד שיוצגו כמו השיקים שהוצעו כבודדים
ואת הבודדים להקטין טיפה את הכפתורים או להזיז אותם ימינה טיפה כדי שלא יקפצו ככה

![image](https://cloud.githubusercontent.com/assets/13170174/9023026/c44602d6-3893-11e5-907c-46b295a21018.png)

**Comment by iddanh** [comment]
כאילו להציג קבוצה של שיקים בשורה אחת?

**Comment by Sabanini** [comment]
בעמוד למעקב ביצוע זה לא מעניין אם זה קבוצה או לא. הם צריכים לתת משוב על מה
קרה על כל שיק ושיק.
כן אמרנו שניתן להם יכולת לסמן מס שיקים ולתת עליהם משוב במאוחד.
זא שאת הכפתורים צריך להציג פעם אחת בלבד. ורק מה שמסומן רלוונטי ללחיצה
בתאריך 2 באוג׳ 2015 18:14,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
אני מתאר את המצב שאני מדמיין, תגיד מה לשנות
העמוד יופרד לשני חלקים:
* קבוצות שיקים
* שיקים בודדים

#### קבוצות שיקים 
כל עסקה תוצג בשורה אחת עם הכפתורים
* עסקה בוצעה
* בוצעה בתנאים אחרים
* חלק מהשיקים לא נכללו בעסקה

 במקרה הזה הוא יועבר לדף אחר שבו הוא יכול לסמן איזה שיקים היו בעסקה 
 השיקים שלא סומנו כאן יעברו לחלק של שיקים בודדים ואז שם יש אופציה לספר לנו מה קרה עם העסקה הזאת
* עסקה לא בוצעה

#### שיקים בודדים
ישאר כמו שזה עכשיו

איך זה נשמע?

**Comment by Sabanini** [comment]
לא.

כל השיקים מופיעים גם בלמעקב ביצוע וגם בצד לקוח בעסקאות מאושרות כמו הרשימה
של השיקים הבודדים.

אממה יש להם צ'ק בוקס

מתחת להכל יש כפתורים.

המשתמש מסמן מה שהוא רוצה לדווח עליו ולוחץ.

בוצעה בתנאים אחרים לא יעבוד אם ילחצו על יותר משיק אחד. אבל בוצעה ונדחתה אין
בעיה לסמן את כל השיקים. ולדווח עליהם
בתאריך 2 באוג׳ 2015 18:24,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
המשתמש לא ירצה לראות את הקבוצות ביחד?
בתצוגה הזאת אין לו שום אינדיקציה שהם היו חלק מקבוצה
הוא גם לא ידע מה לכתוב בעמלת העברה על כל שיק כי זה אמור להיות רק פעם אחת על קבוצה...

**Comment by Sabanini** [comment]
אתה צודק. שניה
בתאריך 2 באוג׳ 2015 18:36,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
אז מה לגבי זה?

**Comment by Sabanini** [comment]
תעשה כמו שאתה כתבת.
לגבי ההפרד. בין בודדים לקבוצה.

צריך עם זאת לחשוב איך נותנים לו יכולת לתקן הצעה שנעשתה בנתונים אחרים..

ייתכן שכרגע נדע שאי אפשר ונשאיר את זה לגרסא הבאה אלא אם יש לך רעיון קליל לזה
בתאריך 5 באוג׳ 2015 21:47,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
הוספתי סוגיה חדשה #81
