### ISSUE TITLE
הוספת תאריך ושעה בעמודים מסויימים - בצד ספק

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#78]
### כשספק נכנס לעמוד הצעות מחיר שנדחו
מופיעות לו כל הצעות המחיר שהעלה ושהלקוח לא בחר בהן ובחר הצעה אחרת
כאשר הוא לוחץ על שם הלקוח (ולא על הח.פ. שלו
 נפתח לו צילום השיק פה צריכים להופיע כל הפרטים לגבי אותה הצעת מחיר ומה קרה איתה
- [x] ז"א שצריכים להציג לו את ההצעה שלו את ההצעה שניצחה
- [x] את השעה והתאריך בו הלקוח העלה את השיק
- [x] את השעה והתאריך שהוא העלה את ההצעה
- [x] את השעה והתאריך שהספק האחר העלה את ההצעה מטעמו
- [x] ואת השעה והתאריך בו הלקוח אישר את ההצעה המנצחת

תאריך ושעה צריכים להיות בקוביה אחת קטנה באותה עמודה ולא בשתיים
זה עמוד שאין בו הרבה פרטים אז ניתן לדחוף את כל הפרטים האלו כדי שיוכל ללמוד להבא
איך להתייעל
את צילום השיק ניתן לדחוף מעט למטה ולהציג את כל הפרטים שציינתי מתחת לפרטי השיק בטבלה ברורה ומסודרת בשילוב צבעים של ההצעה שלו באדום
ואת ההצעה שניצחה בירוק

עמוד נוסף בו חשוב להציג לו את התאריך והשעה הוא 
### עמוד ממתינות לאישור
כדי שיהיה לכך מקום ניתן להשמיט את העמודות הבאות מן העמוד הזה:
- [x] דמי טיפול
- [x] עמלה
- [x] ימי ערך
- [x] ריבית מצטברת

את סך הריבית בעמוד הזה צריך לשנות לסה"כ עמלות - שזה למעשה סך כל החיובים עמלות וריבית כולל מע"מ 
ואז את הנטו

במקום שמתפנה בתחילת הטבלה מצד ימין 
- [x] יש להוסיף את השעה והתאריך שבה אותו ספק
הציע

### בעמוד למעקב ביצוע
כשמופיע שיק - והספק אמור לדווח מה קרה איתו
לפעמים הוא מרגיש שהשיק נמצא שם כבר תקופה
אז אם הוא לוחץ על שם הלקוח נפתח לו השיק
עם תמונתו וכל פרטיו
בעמוד הזה
- [x] יש להוסיף גם את השעה והתאריך שבהם ההצעה הועלתה
- [x] ואת השעה והתאריך בהם הלקוח אישר אותה

זאת כדי לאפשר לו יכולת מעקב אמיתית על השיקים שאמורים להגיע אליו וטרם הגיעו

בעניין הזה
- [x] הייתי מוסיף ברישום לקוח ובעדכון פרטים אישיים חלונית בחירה - כלומר לא חובה
לנייד של נציג העסק

וכך בעמוד הזה שבו ספק בוחן את פרטי העסקה שאמורה להגיע אליו
- [x] יוצג לו גם פרטיו של נציג הלקוח ובינהם גם הנייד שלו
ואז אם ישנה בעיה הספק יוכל להתקשר ללקוח לשאול אותו מתי הוא מגיע..

סתם דוגמא אם הוא עומד לסגור או משהו כזה..

### עמוד עסקאות שבוצעו
כאן יש להוסיף כבר בטבלה הראשית את התאריך שבו הספק דיווח על העסקה
זה לא יהיה בהכרח התאריך בה בוצעה העסקה פיזית - ולכן הכותרת צריכה להיות שונה
לדוגמא:
 תאריך אישרור העסקה 
או
- [x] דווח שבוצע ביום
ואז למטה התאריך

אותו דבר בדיוק 
### בעמוד עסקאות שבוטלו
- [x] done

###  בעמוד שיקים שנדחו
יש להוסיף עמודה בתחילתו 
- [x] 'נדחה ביום'
ואז את התאריך למטה

### עמוד שיקים חדשים
כשספק לוחץ על שיק נפתח לו עמוד הצעת מחיר
עם המחשבון וכו
בעמוד הזה ניתן להציג לו את הפרטיםן הבאים
- [x] הועלה בשעה ותאריך
- [x] נמצע במערכת - ככה וככה שעות...

**Comment by iddanh** [comment]
בגלל באג לכל השיקים שאושרו לפני אתמול לא נשמר התאריך שהם אושרו
עכשיו זה מתוקן אז אין צורך לפתוח על זה באג
(אלא אם זה לא באמת מתוקן עכשיו חחחח)
