### ISSUE TITLE
עמוד ממתינות לאישור 

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#8]
- [x] בעמוד ממתינות לאישור ועמוד למעקב ביצוע - הורדת שלושת האפסים מהסכומים בריבית ובנטו והרחקת הש"ח מהמספר
- [x] כמו כן יש לשנות את הכותרת שיעור ריבית 
ולכתוב במקום 'ריבית מצטבר'

## פעולות בעמוד ממתינות לאישור
הטבלה כאן צריכה להכיל את העמודות הבאות בלבד:
שם ,לקוח, ח.פ.לקוח, שם המושך, ח.פ. מושך, תאריך פירעון, ימי ערך, ערך נקוב, סה"כ עמלה, סכום נטו, זמן באויר

### כפתורים בהמשך השורה
עדכן הצעה
מוביל אותו לעמוד הצעת מחיר רגילה
אבל עם הפרמטרים שהוצעו קודם לכן

בטל הצעה
וצריך להיות לו חלונית "האם אתה בטוח?"

אם הספק רוצה לראות פנימה את ההצעה עצמה ולא רק את סה"כ העמלות הוא לוחץ על השיק או על עדכן שיק ומגיע לכלל הפרמטרים שהוצעו..
שם הוא יכול גם לעדכן אותם
עם המחשבון המהמם

**Comment by iddanh** [comment]
לא הבנתי את המשימה הראשונה
