### ISSUE TITLE
צד לקוח, ריבית אפקטיבית גבוה יותר מופיעה לפני נמוכה יותר

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#83]
![image](https://cloud.githubusercontent.com/assets/13170174/9152653/de49873e-3e38-11e5-84c1-74e6b7668013.png)

**Comment by Sabanini** [comment]
עידכנת את זה כבר?
בתאריך 9 באוג׳ 2015 20:25,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
עוד לא העלתי
