### ISSUE TITLE
הערת עיצוב חשובה

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#85]
את כל הכותרות במערכת צריך לצמצם כך שאם ישנה כותרת המורכבת משתי מילים המילים יהיו אחת מעל השניה - 
כמו בדוגמא שמופיעה כאן
עמלת טיפול זה טוב
מסמכים נדרשים זה לא טוב
כך יחסך מקום משמעותי בטבלה
(לדוגמא: 
ריבית אפקטיבית (למעלה) חודשית/שנתית (למטה

![image](https://cloud.githubusercontent.com/assets/13170174/9155148/0edc9f34-3eb7-11e5-94ae-6114e92a332d.png)

**Comment by iddanh** [comment]
אני לא יכול לעשות את זה בשינוי גורף על כל האתר
מה שאני כן יכול לעשות זה שאחרי כל מילה זה ירד שורה, וזה לא תמיד נראה טוב
נגיד במקרה של מס' ימי ערך

בשביל לעשות את מה שאתה רוצה אני צריך ידנית להוסיף סימן שאומר לרדת שורה בכל כותרת...

**Comment by Sabanini** [comment]
תגיד להחליף מיקום בין עמודות זה מסובך?
אני שוקל להחליף בין הנטו לריביות בסוף השורה.
של הצעת המחיר כדי שרשימת הנטו יהיו מעל הטוטל.
בתאריך 9 באוג׳ 2015 21:43,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
אני פשוט עושה את זה ידנית
אז אם זה לא יותר מדי לשנות זה לא נורא

**Comment by iddanh** [comment]
אז מה לגבי זה?

**Comment by Sabanini** [comment]
תפצל רק עמודת ריבית אפקטיבית בעמודים שמופיעה
לדעתי זה הכי דחוף ובעייתי כל היתר בינתיים נראה אש
בתאריך 12 באוג׳ 2015 22:35,‏ "iddanh" <notifications@github.com> כתב:

**Comment by Sabanini** [comment]
הפיצול חשוב גם ברבית הרגילה - כי הכותרת ארוכה
