### ISSUE TITLE
באג - טעות חישוב

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#88]
שים לב שכל הריביות שמופיעות בסוף כל שיק בקבוצה שנבחרה גבוהות מהממוצע למטה
כך שלא יכול להיות שהן מרכיבות אותו
הן כנראה הריביות האפקטיביות של כל שיק ושיק בלי להתיחס לקבוצה
שלוקחת בחשבון עמלת העברה אחת

זה נראה לא הגיוני במבט ראשוני..

![image](https://cloud.githubusercontent.com/assets/13170174/9161822/c0f20850-3f4b-11e5-88e4-07eaa948e559.png)

צריך לשנות את זה כך שהריביות האפקטיביות כשלוחצים על בדיקת קבוצה יהיו האפקטיביות רק עם עמלת הטיפול
בלי עמלת העברה
ואז להוסיף לעמלה שלהן את החלקיות של עמלת העברה המשותפת כדי להציג את הריבית האפקטיבית האמיתית של כל שיק

לגודמא 
אם יש לנו שלושה שיקים של 30 אש"ח ועמלת העברה היא 90
אז העמלה שתצטרף לכל שיק בקבוצה תהיה 30

אם עמלת העברה היא 100 ש"ח
ויש לנו שלושה שיקים של 25,40,35  אש"ח
אז עמלת העברה תצטרף לשיקים באופן הבא 25,40,35 ש"ח בהתאמה

כלומר תתחלק באופן יחסי על השיקים
כדי להעניק להם את הריבית האמיתית שיש להם בקבוצה
ואז אני מאמין שהריביות שיופיעו בסוף השורה יראו כאילו הן מרכיבות את הריבית הממוצעת החודשית

**Comment by iddanh** [comment]
הוספתי את התיקון שרשמת פה וזה עדיין לא נראה נכון...
אני לא מבין מה אני לא עושה בסדר
(אני אראה לך קוד מפושט כדי שתראה לי איפה אני טועה)
##### ככה אני מחשב את הריבית האפקטיבית לכל שיק
```javascript
((totalCommission + totalVat - transferFee) + groupFee * (amount / groupAmount) / finalValue) / (days / 30);
````

##### ככה אני מחשב את האפקטיבית של הקבוצה
```javascript
(groupTotalCommission + groupTotalVat) / groupFinalValue / (groupAverageDays / 30);
````

**Comment by iddanh** [comment]
איך זה נראה עכשיו?

**Comment by iddanh** [comment]
אפשר לסגור את הסוגיה?

**Comment by Sabanini** [comment]
חיובי
בתאריך 18 באוג׳ 2015 19:08,‏ "iddanh" <notifications@github.com> כתב:
