### ISSUE TITLE
חשוב !!! הוספת עמוד - עסקאות שבוצעו

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#9]
בעמוד למעקב ביצוע
צריך להוסיף כפתור שמנקה את השיק מהרשימה ומעבירו לעסקאות שבוצעו

כמו שאמרנו במסגרת העידכון שהעסקה בוצעה צריך שיהיה לו אפשרות לומר לנו מה היו התנאים האמיתיים שלבסוף העסקה בוצעה..
כלומר אם בוצעה בדיוק כפי שהוצע מלכתחילה אז זה קל

אבל אם בפועל נעשתה עיסקה ששונה מההצעה המקורית

הספק יצטרך למלא את הפרטים המעודכנים
וכאן למעשה צריך להחזיר אותו לעמוד של ההצעת מחיר אבל הכותרת צריכה להיות  שונה 
'עידכון הצעת מחיר שבוצעה'

כי אנחנו נוציא חיוב לספק בהתאם לדיווח הנ"ל

בנוסף צריך להיות כפתור שמעדכן את בילי אם הלקוח הגיע לספק וזה החליט על פי מראה וראיון במקום לא לבצע פתאום את העסקה..

כמה שזה לא נעים צריך לאפשר לו לדווח על כך..

חוזר על עצמו בסוגיה #35
חוזר על עצמו בסוגיה #27

**Comment by Sabanini** [comment]
בעמוד הצעות שבוצעו 
תהינה טבלה שמציגה את העסקה המלאה שבוצעה עם כל הפרמטרים המועדכנים כפי שהספק דיווח כולל המסמכים שהביא הלקוח וכו..
ואצל האדמין יהיה מעקב אחר העמוד הזה - כדי שנוכל להוציא חיובים בהתאם..

ומהעמוד הזה ישודר הלאה ליתר העמודים מה ההיסטוריה של אותו שיק תחת אותו לקוח

במקום שבו כתבתי קודם שנרצה למכור הרשאות למידע..
אז המידע שיופיע בעמוד הזה - בנוגע לשיקים שספקים אחרים ביצעו יהיה נתון לשליטתנו את להציג לאחרים או לאו..
וכמה לגבות על כך..

**Comment by iddanh** [comment]
- [ ] להוסיף את החלק של האדמין
