### ISSUE TITLE
בהרשמת לקוח 

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#91]
- [x] להוסיף חלונית כתובת העסק - זו הכתובת הרלוונטית למרחק מהספק 

- [x] להוריד את הכוכבית מהחלונית - מחזור העסק

- [x] כשלקוח נרשם בפעם הראשונה צריך שהחלון הראשון שנפתח לו הוא העלאת שיק 

- [x] לשנות את גוון הכפתור השני בעמוד הצעות מחיר - הם באותו כחול ולא מבדילים

**Comment by iddanh** [comment]
יש כבר כתובת בפרטי נציג העסק שאני משתמש בשביל המרחק
להזיז את זה להיות תחת פרטי העסק?

**Comment by Sabanini** [comment]
צריך להיות גם וגם
אבל רק הכתובת של בית העסק היא שרלוונטית למרחק בינו לספק

החלונית של כתובת הנציג לא רלוונטית למרחק - אבל טוב שיהיה בה את הפיצ'ר של
גוגל מאפ שמאפשר כתובת מדוייקת



בתאריך 11 באוגוסט 2015 בשעה 21:05, מאת iddanh <notifications@github.com>:
