### ISSUE TITLE
שינויי מיקום עמודות בעמודים נבחרים

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#93]
בעמוד הזה יש לשנות את הסדר של העמודות

![image](https://cloud.githubusercontent.com/assets/13170174/9173037/1ebc3698-3f80-11e5-9e14-954684836bf9.png)

- [x]  הסכום נטו צריך להתחלף עם הריביות האפקטיביות ולהיות אחרון משמאל 

- [x] בנוסף צריך להוסיף את הסה"כ עמלות בעסקה כולל עמלת העברה בין הברוטו לנטו
כך שהחיסור בין זה לזה יתן את הסה"כ לתשלום  - כמו בתמונה מטה

- [x] בנוסף צריך גם כאן להוסיף את אמצעי התשלום של הספק הספציפי שהצעתו מופיעה כאן - שהוא לטענתנו ההצעה הטובה ביותר שיש על השיקים הנבחרים כי אם לקוח רוצה לקבל כבר החלטה הוא רוצה לדעת איך יקבל את הכסף

- [x] אם ניתן להוסיף ריבוע קטן  עם סה"כ ריבית-

יכול להיות נחמד 
כמו בתמונה הבאה
![image](https://cloud.githubusercontent.com/assets/13170174/9173357/4d6e4362-3f82-11e5-882e-59edade22478.png)

- [x] בעמוד הזה יש לשנות את סדר העמודות

![image](https://cloud.githubusercontent.com/assets/13170174/9173427/bc8621e8-3f82-11e5-95c6-b7f5d47b0107.png)

באופן הבא:
- [x] שם המושך, ת.פירעון, ערך נקוב, מס' ימי ערך, ריבית חודשית/שנתית, סך הריבית, עמלת טיפול, ריבית אפקטיבית חודשית/שנתית, סכום נטו-בירוק

- [x] יש כאן תוספת קטנה דרושה - להכפיל את הריבית הרגילה ב12 - כדי שזה ייתן ריבית שנתית
ושתופיע בעמודה החמישית עם לוכסן יחד עם הריבית הרגילה

- [x] בנוסף יש להוסיף את הסה"כ עמלות כולל עמלת העברה מתחת לסכום ברוטו ומעל הסכום נטו 
כך שהחיסור בינהם  יתן את אותה תוצאה 

כמו בתמונה הבאה

![image](https://cloud.githubusercontent.com/assets/13170174/9173357/4d6e4362-3f82-11e5-882e-59edade22478.png)

**Comment by Sabanini** [comment]
בא לך לעדכן כדי שאסתכל?
בתאריך 11 באוג׳ 2015 22:17,‏ "iddanh" <notifications@github.com> כתב:

**Comment by iddanh** [comment]
מעודכן
