### ISSUE TITLE
מעולה מה שעשית עם הצגת שיק בודד בתוך קבוצה!!! יופי יופי 

### ISSUE THREAD

**Issue by Sabanini** [iddanh/BillyDemo#96]

**Comment by iddanh** [comment]
איזה חלק? חחחח

**Comment by Sabanini** [comment]
בדיקת שיק בודד בעמוד של קיבוץ קבוצת שיקים
כך שזה מעביר את המסך צפיה כבר לרשימה המפורטת של אותו שיק..
